# このファイルは元のApache 2.0ライセンスのコードから新規に追加されています
# 変更日: 2026-06-28
# 変更者: totto2727
# 変更内容: Makefile に代わる運用スクリプト管理を追加

default:
    @just --list

dialyzer:
    mix dialyzer --format short

e2e:
    SYMPHONY_RUN_LIVE_E2E=1 mix test test/symphony_elixir/live_e2e_test.exs
