defmodule OpencodeClient.Client do
  @moduledoc """
  Req-based transport for generated OpenCode operation modules.

  Endpoint functions are generated by `oapi_generator`; this module only executes the
  request maps emitted by those generated functions.
  """

  @type operation :: %{
          required(:method) => atom,
          required(:url) => String.t(),
          optional(:body) => term,
          optional(:query) => keyword,
          optional(:opts) => keyword,
          optional(:response) => list
        }

  @spec request(operation) :: {:ok, term} | :ok | {:error, term}
  def request(operation) when is_map(operation) do
    method = Map.fetch!(operation, :method)
    url = Map.fetch!(operation, :url)
    body = Map.get(operation, :body)
    query = Map.get(operation, :query, [])
    opts = Map.get(operation, :opts, [])

    req =
      Req.new(
        base_url: Keyword.get(opts, :base_url, OpencodeClient.Config.base_url()),
        method: method,
        url: url,
        json: body,
        params: query
      )
      |> OpencodeClient.Auth.apply(Keyword.get(opts, :auth, OpencodeClient.Config.auth()))

    with {:ok, response} <- Req.request(req) do
      handle_response(response)
    end
  end

  defp handle_response(%{status: status, body: body}) when status in 200..299 do
    case {status, body} do
      {204, _body} -> :ok
      {_status, body} -> {:ok, body}
    end
  end

  defp handle_response(%{status: status, body: body}) do
    {:error, %{status: status, body: body}}
  end

end
