[marketplaces.totto2727]
source_type = "local"
source = "."

[plugins."totto2727@totto2727"]
enabled = true

[plugins."totto2727-dev-flow@totto2727"]
enabled = true

[plugins."totto2727-coding@totto2727"]
enabled = true

[plugins."external-search@totto2727"]
enabled = true

[mcp_servers.linear]
command = "linear-mcp"
args = []

