/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { Generated } from "kysely";

export interface Item {
  default_not_null: Generated<string>;
  default_nullable: Generated<string | null>;
  plain: string;
  plain_nullable: string | null;
}

export interface DB {
  item: Item;
}
