import handle from "hono-react-router-adapter/cloudflare-workers"
import app from "#@/server.js"
import { getLoadContext } from "#@/types/react-router.js"
// @ts-ignore -- generated by vite
import * as build from "./build/server"

export default handle(build, app, { getLoadContext })
