packages:
  - app/*
  - config/*
  - infra/*
  - package/*

catalogMode: strict
catalogs:
  build:
    "@rslib/core": ^0.14.0
    "@typescript/native-preview": 7.0.0-dev.20250923.1
    typescript: ^5.9.2
    vite: ^7.0.0
  clerk:
    "@clerk/backend": ^2.0.0
    "@clerk/react-router": ^1.4.7
    "@hono/clerk-auth": ^3.0.0
  cli:
    pncat: ^0.5.0
    tsx: ^4.19.4
    turbo: ^2.5.3
  cloudflare:
    "@cloudflare/vite-plugin": ^1.11.0
    "@cloudflare/workers-oauth-provider": ^0.0.10
    "@cloudflare/workers-types": ^4.20250813.0
    wrangler: 4.38.0
  dev:
    "@modelcontextprotocol/sdk": ^1.0.0
    "@socotra/modelcontextprotocol-sdk": ^1.18.0
    "@types/node": ^24.1.0
    agents: ^0.1.0
    isbot: ^5.1.28
  drizzle:
    "@libsql/client": ^0.15.7
    drizzle-cuid2: ^2.1.0
    drizzle-kit: ^0.31.1
    drizzle-orm: ^0.44.0
  hono:
    "@hono/mcp": ^0.1.1
    "@hono/standard-validator": ^0.1.4
    "@hono/vite-dev-server": ^0.21.0
    hono: ^4.7.10
    hono-react-router-adapter: ^0.6.5
  lint:
    "@biomejs/biome": 2.2.4
    dprint: ^0.50.0
  pulumi:
    "@pulumi/aws": ^7.0.0
    "@pulumi/awsx": ^3.0.0
    "@pulumi/cloudflare": ^6.5.0
    "@pulumi/pulumi": ^3.113.0
  react:
    "@react-router/cloudflare": ^7.6.0
    "@react-router/dev": ^7.6.0
    "@react-router/fs-routes": ^7.6.0
    "@types/react": ^19.1.5
    "@types/react-dom": ^19.1.5
    react: ^19.1.0
    react-dom: ^19.1.0
    react-router: ^7.6.0
  test:
    "@playwright/test": ^1.52.0
    "@rstest/core": ^0.4.0
  tsconfig:
    "@tsconfig/node24": ^24.0.0
    "@tsconfig/remix": ^2.0.5
    "@tsconfig/strictest": ^2.0.5
  ui:
    "@tailwindcss/cli": ^4.1.11
    "@yamada-ui/calendar": ^1.8.16
    "@yamada-ui/charts": ^1.5.15
    "@yamada-ui/react": ^1.7.6
    "@yamada-ui/table": ^1.3.13
    daisyui: ^5.0.50
    tailwindcss: ^4.1.11
  util:
    "@totto/function": jsr:^1.5.5
    zod: ^4.0.0
