packages:
  - app/*
  - config/*
  - infra/*
  - package/*
catalogs:
  build:
    "@rsbuild/plugin-react": ^1.4.1
    "@rslib/core": ^0.14.0
    "@typescript/native-preview": 7.0.0-dev.20250923.1
    typescript: ^5.9.2
    vite: ^7.0.0
    vite-tsconfig-paths: ^5.1.4
  casbin:
    "@hono/casbin": ^1.0.0
    casbin: ^5.39.0
  cli:
    pncat: ^0.5.0
    turbo: ^2.5.3
  cloudflare:
    "@cloudflare/vite-plugin": ^1.11.0
    "@cloudflare/workers-oauth-provider": ^0.0.10
    "@cloudflare/workers-types": ^4.20250813.0
    wrangler: 4.38.0
  dev:
    "@mikaelporttila/rss": jsr:^1.1.3
    "@modelcontextprotocol/sdk": ^1.0.0
    "@socotra/modelcontextprotocol-sdk": ^1.18.0
    "@types/node": ^24.1.0
    agents: ^0.1.0
  drizzle:
    drizzle-cuid2: ^2.1.0
    drizzle-kit: ^0.31.1
    drizzle-orm: ^0.44.0
  graphql:
    "@pothos/core": ^4.9.1
    "@pothos/plugin-validation": ^4.1.1
    graphql: ^16.11.0
    graphql-scalars: ^1.24.2
  hono:
    "@hono/graphql-server": ^0.7.0
    "@hono/mcp": ^0.1.1
    "@hono/standard-validator": ^0.1.4
    hono: ^4.7.10
  lint:
    "@biomejs/biome": 2.2.4
    dprint: ^0.50.0
  pulumi:
    "@pulumi/aws": ^7.0.0
    "@pulumi/awsx": ^3.0.0
    "@pulumi/cloudflare": ^6.5.0
    "@pulumi/pulumi": ^3.113.0
  test:
    "@rstest/core": ^0.4.0
  tsconfig:
    "@tsconfig/node24": ^24.0.0
    "@tsconfig/remix": ^2.0.5
    "@tsconfig/strictest": ^2.0.5
  ui:
    "@tailwindcss/cli": ^4.1.11
    "@tailwindcss/vite": ^4.1.14
    daisyui: ^5.1.27
    tailwind: ^4.0.0
    tailwindcss: ^4.1.11
  util:
    "@totto/function": jsr:^1.7.0
    zod: ^4.0.0
