$schema: https://pnpm.io/pnpm-workspace_yaml
packages:
  - app/*
  - config/*
catalogMode: strict
catalog:
  "@biomejs/biome": 2.0.6
  "@clerk/backend": ^1.33.1
  "@clerk/react-router": ^1.4.7
  "@cloudflare/vite-plugin": ^1.11.0
  "@cloudflare/workers-types": ^4.20250525.0
  "@hono/clerk-auth": ^2.0.0
  "@hono/mcp": ^0.1.1
  "@hono/vite-dev-server": ^0.19.1
  "@libsql/client": ^0.15.7
  "@modelcontextprotocol/sdk": ^1.0.0
  "@playwright/test": ^1.52.0
  "@react-router/cloudflare": ^7.6.0
  "@react-router/dev": ^7.6.0
  "@react-router/fs-routes": ^7.6.0
  "@tailwindcss/cli": ^4.1.11
  "@totto/function": jsr:^1.4.0
  "@tsconfig/node24": ^24.0.0
  "@tsconfig/remix": ^2.0.5
  "@tsconfig/strictest": ^2.0.5
  "@types/node": ^24.1.0
  "@types/react": ^19.1.5
  "@types/react-dom": ^19.1.5
  "@yamada-ui/calendar": ^1.8.16
  "@yamada-ui/charts": ^1.5.15
  "@yamada-ui/react": ^1.7.6
  "@yamada-ui/table": ^1.3.13
  daisyui: ^5.0.50
  dprint: ^0.50.0
  drizzle-cuid2: ^2.1.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.43.1
  hono: ^4.7.10
  hono-react-router-adapter: ^0.6.5
  isbot: ^5.1.28
  react: ^19.1.0
  react-dom: ^19.1.0
  react-router: ^7.6.0
  tailwindcss: ^4.1.11
  tsx: ^4.19.4
  turbo: ^2.5.3
  typescript: ^5.8.3
  vite: ^6.3.5
  wrangler: ^4.27.0
  zod: ^3.24.1
