packages:
  - app/*
  - config/*
  - infra/*
catalogMode: strict
catalogs:
  automation:
    "@playwright/test": ^1.52.0
  backend:
    drizzle-cuid2: ^2.1.0
    drizzle-kit: ^0.31.1
    drizzle-orm: ^0.43.1
  build:
    "@cloudflare/vite-plugin": ^1.11.0
    "@hono/vite-dev-server": ^0.19.1
    vite: ^6.3.5
  dev:
    "@clerk/backend": ^1.33.1
    "@clerk/react-router": ^1.4.7
    "@cloudflare/workers-oauth-provider": ^0.0.6
    "@cloudflare/workers-types": ^4.20250525.0
    "@formatjs/intl-durationformat": ^0.7.4
    "@hono/clerk-auth": ^2.0.0
    "@hono/mcp": ^0.1.1
    "@hono/standard-validator": ^0.1.4
    "@libsql/client": ^0.15.7
    "@modelcontextprotocol/sdk": ^1.0.0
    "@pulumi/cloudflare": ^6.5.0
    "@pulumi/pulumi": ^3.113.0
    "@react-router/cloudflare": ^7.6.0
    "@react-router/dev": ^7.6.0
    "@react-router/fs-routes": ^7.6.0
    "@totto/function": jsr:^1.4.0
    "@tsconfig/node24": ^24.0.0
    "@tsconfig/remix": ^2.0.5
    "@tsconfig/strictest": ^2.0.5
    "@yamada-ui/calendar": ^1.8.16
    "@yamada-ui/charts": ^1.5.15
    "@yamada-ui/react": ^1.7.6
    "@yamada-ui/table": ^1.3.13
    agents: ^0.0.113
    daisyui: ^5.0.50
    dprint: ^0.50.0
    hono: ^4.7.10
    hono-react-router-adapter: ^0.6.5
    isbot: ^5.1.28
    react: ^19.1.0
    react-dom: ^19.1.0
    react-router: ^7.6.0
    typescript: ^5.8.3
    wrangler: 4.30.0
  lint:
    "@biomejs/biome": 2.0.6
  monorepo:
    turbo: ^2.5.3
  network:
    "@pulumi/aws": ^7.0.0
    "@pulumi/awsx": ^3.0.0
  script:
    tsx: ^4.19.4
  style:
    "@tailwindcss/cli": ^4.1.11
    tailwindcss: ^4.1.11
  types:
    "@types/node": ^24.1.0
    "@types/react": ^19.1.5
    "@types/react-dom": ^19.1.5
  utils:
    zod: ^3.24.1
