packages:
  - app/*
  - config/*
  - infra/*
  - package/*
catalogs:
  build:
    "@typescript/native-preview": 7.0.0-dev.20250923.1
    "@vitejs/plugin-react": ^5.0.4
    tsdown: ^0.15.7
    typescript: ^5.9.2
    vite: npm:rolldown-vite@^7.0.0
    vite-tsconfig-paths: ^5.1.4
  casbin:
    "@hono/casbin": ^1.0.0
    casbin: ^5.39.0
  cli:
    pncat: ^0.6.0
    turbo: ^2.5.3
  cloudflare:
    "@cloudflare/vite-plugin": ^1.11.0
    "@cloudflare/workers-oauth-provider": ^0.0.11
    "@cloudflare/workers-types": ^4.20250813.0
    wrangler: 4.42.2
  dev:
    "@mikaelporttila/rss": jsr:^1.1.3
    "@modelcontextprotocol/sdk": ^1.0.0
    "@socotra/modelcontextprotocol-sdk": ^1.18.0
    "@types/node": ^24.1.0
    agents: ^0.2.0
    tailwind: ^4.0.0
  drizzle:
    drizzle-cuid2: ^2.1.0
    drizzle-kit: ^0.31.5
    drizzle-orm: ^0.44.6
  graphql:
    "@pothos/core": ^4.9.1
    "@pothos/plugin-validation": ^4.1.1
    graphql: ^16.11.0
    graphql-scalars: ^1.24.2
  hono:
    "@hono/cloudflare-access": ^0.3.1
    "@hono/graphql-server": ^0.7.0
    "@hono/mcp": ^0.1.1
    "@hono/standard-validator": ^0.1.4
    hono: ^4.7.10
  lint:
    "@biomejs/biome": 2.2.6
    dprint: ^0.50.0
    eslint: ^9.37.0
    eslint-config-flat-gitignore: ^2.1.0
    eslint-plugin-react-hooks: ^7.0.0
    typescript-eslint: ^8.46.1
  pulumi:
    "@pulumi/aws": ^7.0.0
    "@pulumi/awsx": ^3.0.0
    "@pulumi/cloudflare": ^6.5.0
    "@pulumi/pulumi": ^3.113.0
  react:
    "@tanstack/react-router": ^1.133.3
    "@tanstack/react-router-devtools": ^1.133.3
    "@tanstack/react-start": ^1.133.3
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    babel-plugin-react-compiler: ^1.0.0
    react: ^19.2.0
    react-dom: ^19.2.0
  test:
    vitest: ^3.2.4
  tsconfig:
    "@tsconfig/strictest": ^2.0.5
  ui:
    "@iconify-json/material-symbols": ^1.2.41
    "@svgr/core": ^8.1.0
    "@svgr/plugin-jsx": ^8.1.0
    "@tailwindcss/cli": ^4.1.11
    "@tailwindcss/vite": ^4.1.14
    "@yamada-ui/react": ^1.7.8
    daisyui: ^5.1.27
    tailwindcss: ^4.1.11
    unplugin-icons: ^22.4.2
  util:
    "@totto/function": jsr:^1.7.3
    zod: ^4.0.0
