# https://taskfile.dev
version: '3'

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  template:
    cmd: na turbo gen -c template/src/config.cts {{.CLI_ARGS}}

  precommit:
    cmd: na turbo fix check test build
