# https://taskfile.dev
version: '3'

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  docker:build:sandbox:
    deps:
      - docker:build:sandbox-base
    cmds:
      - docker build --progress=plain -t ghcr.io/totto2727-org/monorepo/sandbox:latest -f ./sandbox/Dockerfile ./sandbox

  docker:build:sandbox-base:
    cmds:
      - docker build --progress=plain -t ghcr.io/totto2727-org/monorepo/sandbox-base:latest -f ./docker/sandbox-base.Dockerfile ./docker

  docker:run:base:
    cmds:
      - docker run --rm -it sandbox-base:latest

  docker:run:
    cmds:
      - docker run --rm -it monorepo-sandbox:latest

  docker:push:
    deps:
      - docker:build:sandbox
      - docker:build:sandbox-base
    cmds:
      - docker push ghcr.io/totto2727-org/monorepo/sandbox:latest
      - docker push ghcr.io/totto2727-org/monorepo/sandbox-base:latest
