name: Setup devbox
description: Install devbox with cache enabled. Subsequent steps can activate the devbox environment via `eval "$(devbox shellenv)"` and then run the provided tools directly.

runs:
  using: composite
  steps:
    - name: Install devbox
      uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
      with:
        enable-cache: true
