import { stringifyYAML } from 'confbox'
import { Predicate, String } from 'effect'
import ts from 'typescript'

export interface LinkRequest {
  readonly hash: string | undefined
  readonly path: string
  readonly query: string
  readonly text: string | undefined
}

interface CompileMarkdownModuleOptions {
  readonly code: string
  readonly id: string
  readonly resolveLink: (specifier: string) => Promise<string>
}

export interface CompiledMarkdownModule {
  readonly code: string
  readonly source: string
  readonly sourceMap: readonly MarkdownSourcePosition[]
}

export interface MarkdownSourcePosition {
  readonly column: number
  readonly line: number
}

interface StaticObject {
  readonly [key: string]: StaticValue
}
type StaticValue = boolean | null | number | string | StaticValue[] | StaticObject

interface MarkdownMetadata {
  readonly frontmatter?: Readonly<Record<string, StaticValue>>
  readonly frontmatterPosition?: MarkdownSourcePosition
  readonly title: string
  readonly titlePosition: MarkdownSourcePosition
}

interface MappedMarkdown {
  readonly source: string
  readonly sourceMap: readonly MarkdownSourcePosition[]
}

export const generatedFileNotice =
  '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->'

interface StaticMarkdownNote {
  readonly body: string
  readonly index: string
  readonly slug: string
}

interface RenderedMarkdownInterpolation {
  readonly dependency?: string
  readonly value: string
}

interface FormatMarkdownLinkOptions {
  readonly destination: string
  readonly request: LinkRequest
  readonly title: string
}

export class MarkdownCompileError extends Error {
  readonly fileName: string
  override readonly name = 'MarkdownCompileError'

  constructor(fileName: string, message: string) {
    super(`${fileName}: ${message}`)
    this.fileName = fileName
  }
}

export const parseLinkRequest = (id: string): LinkRequest | undefined => {
  const queryIndex = id.indexOf('?')
  if (queryIndex === -1) {
    return undefined
  }

  const path = id.slice(0, queryIndex)
  const query = id.slice(queryIndex + 1)
  const parameters = new URLSearchParams(query)
  if (!path.endsWith('.md.ts') || !parameters.has('link')) {
    return undefined
  }

  return {
    hash: parameters.get('hash') ?? undefined,
    path,
    query,
    text: parameters.get('text') ?? undefined,
  }
}

const escapeLinkText = (text: string): string =>
  text.replaceAll('\\', '\\\\').replaceAll('[', '\\[').replaceAll(']', '\\]')

export const formatMarkdownLink = (options: FormatMarkdownLinkOptions): string => {
  const text = options.request.text ?? options.title
  const hashValue = options.request.hash
  const hash = Predicate.isString(hashValue) && String.isNonEmpty(hashValue) ? `#${encodeURIComponent(hashValue)}` : ''

  return `[${escapeLinkText(text)}](${options.destination}${hash})`
}

const findLinkImports = (sourceFile: ts.SourceFile): ReadonlyMap<string, string> => {
  const imports = new Map<string, string>()

  for (const statement of sourceFile.statements) {
    if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier)) {
      continue
    }

    const request = parseLinkRequest(statement.moduleSpecifier.text)
    const binding = statement.importClause?.name
    if (request && binding) {
      imports.set(binding.text, statement.moduleSpecifier.text)
    }
  }

  return imports
}

const findMarkdownTemplate = (sourceFile: ts.SourceFile): ts.TemplateLiteral => {
  for (const statement of sourceFile.statements) {
    if (!ts.isExportAssignment(statement) || statement.isExportEquals === true) {
      continue
    }

    const { expression } = statement
    if (ts.isTaggedTemplateExpression(expression) && ts.isIdentifier(expression.tag) && expression.tag.text === 'md') {
      return expression.template
    }
  }

  throw new MarkdownCompileError(sourceFile.fileName, 'expected a default export using the md tagged template')
}

const unwrapExpression = (expression: ts.Expression): ts.Expression => {
  if (
    ts.isAsExpression(expression) ||
    ts.isParenthesizedExpression(expression) ||
    ts.isSatisfiesExpression(expression) ||
    ts.isTypeAssertionExpression(expression)
  ) {
    return unwrapExpression(expression.expression)
  }
  return expression
}

const findMetadataObject = (sourceFile: ts.SourceFile): ts.ObjectLiteralExpression | undefined => {
  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue
    }

    const exported =
      ts.getModifiers(statement)?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false
    if (!exported) {
      continue
    }

    for (const declaration of statement.declarationList.declarations) {
      if (ts.isIdentifier(declaration.name) && declaration.name.text === 'meta' && declaration.initializer) {
        const initializer = unwrapExpression(declaration.initializer)
        return ts.isObjectLiteralExpression(initializer) ? initializer : undefined
      }
    }
  }

  return undefined
}

const staticPropertyName = (name: ts.PropertyName): string | undefined =>
  ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name) ? name.text : undefined

const objectProperty = (value: ts.ObjectLiteralExpression, name: string): ts.Expression | undefined => {
  const property = value.properties.find(
    (candidate) => ts.isPropertyAssignment(candidate) && staticPropertyName(candidate.name) === name,
  )
  return property && ts.isPropertyAssignment(property) ? unwrapExpression(property.initializer) : undefined
}

const readNoteBody = (value: ts.Expression, sourceFile: ts.SourceFile): string => {
  if (!ts.isTaggedTemplateExpression(value) || !ts.isIdentifier(value.tag) || value.tag.text !== 'md') {
    throw new MarkdownCompileError(sourceFile.fileName, 'Markdown note bodies must use the md tagged template')
  }
  if (!ts.isNoSubstitutionTemplateLiteral(value.template)) {
    throw new MarkdownCompileError(sourceFile.fileName, 'Markdown note bodies must not contain interpolations')
  }
  return value.template.text.trim()
}

const readNoteCollections = (sourceFile: ts.SourceFile): ReadonlyMap<string, readonly StaticMarkdownNote[]> => {
  const collections = new Map<string, readonly StaticMarkdownNote[]>()

  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue
    }

    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || !declaration.initializer) {
        continue
      }
      const initializer = unwrapExpression(declaration.initializer)
      if (
        !ts.isCallExpression(initializer) ||
        !ts.isIdentifier(initializer.expression) ||
        initializer.expression.text !== 'defineNote'
      ) {
        continue
      }

      const argument = initializer.arguments[0] && unwrapExpression(initializer.arguments[0])
      if (initializer.arguments.length !== 1 || !argument || !ts.isArrayLiteralExpression(argument)) {
        throw new MarkdownCompileError(sourceFile.fileName, 'defineNote must receive one static tuple')
      }

      const slugs = new Set<string>()
      const notes = argument.elements.map((element, position): StaticMarkdownNote => {
        if (ts.isSpreadElement(element)) {
          throw new MarkdownCompileError(sourceFile.fileName, 'defineNote tuples must not contain spread elements')
        }
        const note = unwrapExpression(element)
        if (!ts.isObjectLiteralExpression(note)) {
          throw new MarkdownCompileError(sourceFile.fileName, 'defineNote tuples must contain static objects')
        }

        const slug = objectProperty(note, 'slug')
        const body = objectProperty(note, 'body')
        if (!slug || !ts.isStringLiteralLike(slug)) {
          throw new MarkdownCompileError(sourceFile.fileName, 'Markdown note slugs must be static strings')
        }
        if (!body) {
          throw new MarkdownCompileError(sourceFile.fileName, 'Markdown notes must define a body')
        }
        if (slugs.has(slug.text)) {
          throw new MarkdownCompileError(sourceFile.fileName, `Duplicate Markdown note slug: ${slug.text}`)
        }
        slugs.add(slug.text)
        return { body: readNoteBody(body, sourceFile), index: `${position + 1}`, slug: slug.text }
      })
      collections.set(declaration.name.text, notes)
    }
  }

  return collections
}

const renderNoteInterpolation = (
  expression: ts.CallExpression,
  collections: ReadonlyMap<string, readonly StaticMarkdownNote[]>,
  sourceFile: ts.SourceFile,
): string | undefined => {
  if (
    !ts.isIdentifier(expression.expression) ||
    (expression.expression.text !== 'noteRef' && expression.expression.text !== 'noteBody')
  ) {
    return undefined
  }
  const collectionName = expression.arguments[0] && unwrapExpression(expression.arguments[0])
  const slug = expression.arguments[1] && unwrapExpression(expression.arguments[1])
  if (
    expression.arguments.length !== 2 ||
    !collectionName ||
    !ts.isIdentifier(collectionName) ||
    !slug ||
    !ts.isStringLiteralLike(slug)
  ) {
    throw new MarkdownCompileError(
      sourceFile.fileName,
      `${expression.expression.text} requires notes and a static slug`,
    )
  }

  const notes = collections.get(collectionName.text)
  if (!notes) {
    throw new MarkdownCompileError(sourceFile.fileName, `Unknown Markdown note collection: ${collectionName.text}`)
  }
  const note = notes.find((candidate) => candidate.slug === slug.text)
  if (!note) {
    throw new MarkdownCompileError(sourceFile.fileName, `Unknown Markdown note slug: ${slug.text}`)
  }
  return expression.expression.text === 'noteRef' ? `[^${note.index}]` : `[^${note.index}]: ${note.body}`
}

const renderMarkdownInterpolation = async (
  expression: ts.Expression,
  linkImports: ReadonlyMap<string, string>,
  noteCollections: ReadonlyMap<string, readonly StaticMarkdownNote[]>,
  options: CompileMarkdownModuleOptions,
  sourceFile: ts.SourceFile,
): Promise<RenderedMarkdownInterpolation> => {
  if (ts.isIdentifier(expression)) {
    const specifier = linkImports.get(expression.text)
    if (!Predicate.isString(specifier)) {
      throw new MarkdownCompileError(options.id, `interpolation ${expression.text} is not a ?link default import`)
    }
    return { dependency: specifier, value: await options.resolveLink(specifier) }
  }

  if (ts.isCallExpression(expression)) {
    const note = renderNoteInterpolation(expression, noteCollections, sourceFile)
    if (Predicate.isString(note)) {
      return { value: note }
    }
  }

  throw new MarkdownCompileError(
    options.id,
    'md interpolations must reference a ?link import or a Markdown note helper',
  )
}

const readStaticValue = (expression: ts.Expression, sourceFile: ts.SourceFile): StaticValue => {
  const value = unwrapExpression(expression)
  if (ts.isStringLiteralLike(value)) {
    return value.text
  }
  if (ts.isNumericLiteral(value)) {
    return Number(value.text)
  }
  if (value.kind === ts.SyntaxKind.TrueKeyword) {
    return true
  }
  if (value.kind === ts.SyntaxKind.FalseKeyword) {
    return false
  }
  if (value.kind === ts.SyntaxKind.NullKeyword) {
    return null
  }
  if (ts.isPrefixUnaryExpression(value) && ts.isNumericLiteral(value.operand)) {
    const number = Number(value.operand.text)
    if (value.operator === ts.SyntaxKind.MinusToken) {
      return -number
    }
    if (value.operator === ts.SyntaxKind.PlusToken) {
      return number
    }
  }
  if (ts.isArrayLiteralExpression(value)) {
    return value.elements.map((element) => {
      if (ts.isSpreadElement(element)) {
        throw new MarkdownCompileError(sourceFile.fileName, 'meta.frontmatter must not contain spread elements')
      }
      return readStaticValue(element, sourceFile)
    })
  }
  if (ts.isObjectLiteralExpression(value)) {
    const entries = value.properties.map((property): readonly [string, StaticValue] => {
      if (!ts.isPropertyAssignment(property)) {
        throw new MarkdownCompileError(
          sourceFile.fileName,
          'meta.frontmatter must contain only static property assignments',
        )
      }
      const name = staticPropertyName(property.name)
      if (!Predicate.isString(name)) {
        throw new MarkdownCompileError(sourceFile.fileName, 'meta.frontmatter property names must be static')
      }
      return [name, readStaticValue(property.initializer, sourceFile)]
    })
    return Object.fromEntries(entries)
  }

  throw new MarkdownCompileError(
    sourceFile.fileName,
    'meta.frontmatter values must be static strings, numbers, booleans, null, arrays, or objects',
  )
}

const readStaticObject = (value: ts.ObjectLiteralExpression, sourceFile: ts.SourceFile): StaticObject => {
  const entries = value.properties.map((property): readonly [string, StaticValue] => {
    if (!ts.isPropertyAssignment(property)) {
      throw new MarkdownCompileError(
        sourceFile.fileName,
        'meta.frontmatter must contain only static property assignments',
      )
    }
    const name = staticPropertyName(property.name)
    if (!Predicate.isString(name)) {
      throw new MarkdownCompileError(sourceFile.fileName, 'meta.frontmatter property names must be static')
    }
    return [name, readStaticValue(property.initializer, sourceFile)]
  })
  return Object.fromEntries(entries)
}

const sourcePosition = (sourceFile: ts.SourceFile, position: number): MarkdownSourcePosition => {
  const location = sourceFile.getLineAndCharacterOfPosition(position)
  return { column: location.character + 1, line: location.line + 1 }
}

const readMarkdownMetadata = (sourceFile: ts.SourceFile): MarkdownMetadata => {
  const metadata = findMetadataObject(sourceFile)
  const properties = new Map<string, ts.Expression>()

  for (const property of metadata?.properties ?? []) {
    if (ts.isPropertyAssignment(property)) {
      const name = staticPropertyName(property.name)
      if (Predicate.isString(name)) {
        properties.set(name, unwrapExpression(property.initializer))
      }
    }
  }

  const title = properties.get('title')
  if (!title || !ts.isStringLiteralLike(title)) {
    throw new MarkdownCompileError(sourceFile.fileName, 'expected a static meta.title string')
  }

  const frontmatter = properties.get('frontmatter')
  if (!frontmatter) {
    return { title: title.text, titlePosition: sourcePosition(sourceFile, title.getStart(sourceFile)) }
  }
  if (!ts.isObjectLiteralExpression(frontmatter)) {
    throw new MarkdownCompileError(sourceFile.fileName, 'meta.frontmatter must be a static object')
  }

  return {
    frontmatter: readStaticObject(frontmatter, sourceFile),
    frontmatterPosition: sourcePosition(sourceFile, frontmatter.getStart(sourceFile)),
    title: title.text,
    titlePosition: sourcePosition(sourceFile, title.getStart(sourceFile)),
  }
}

const mappedSource = (source: string, position: MarkdownSourcePosition): MappedMarkdown => ({
  source,
  sourceMap: source.split('\n').map(() => position),
})

const mappedTemplateSource = (source: string, sourceFile: ts.SourceFile, startPosition: number): MappedMarkdown => {
  const start = sourcePosition(sourceFile, startPosition)
  return {
    source,
    sourceMap: source.split('\n').map((_line, index) => ({
      column: index === 0 ? start.column : 1,
      line: start.line + index,
    })),
  }
}

const appendMappedMarkdown = (combined: MappedMarkdown, remaining: readonly MappedMarkdown[]): MappedMarkdown => {
  const [chunk, ...rest] = remaining
  if (!chunk) {
    return combined
  }
  if (String.isEmpty(combined.source)) {
    return appendMappedMarkdown(chunk, rest)
  }

  const previousPosition = combined.sourceMap.at(-1)
  if (!previousPosition) {
    return appendMappedMarkdown(chunk, rest)
  }
  const mergedPosition = combined.source.endsWith('\n') ? (chunk.sourceMap[0] ?? previousPosition) : previousPosition
  return appendMappedMarkdown(
    {
      source: `${combined.source}${chunk.source}`,
      sourceMap: [...combined.sourceMap.slice(0, -1), mergedPosition, ...chunk.sourceMap.slice(1)],
    },
    rest,
  )
}

const concatenateMappedMarkdown = (chunks: readonly MappedMarkdown[]): MappedMarkdown =>
  appendMappedMarkdown({ source: '', sourceMap: [] }, chunks)

const removeLeadingNewlines = (markdown: MappedMarkdown): MappedMarkdown => {
  const leadingNewlines = /^\n+/u.exec(markdown.source)?.[0].length ?? 0
  return {
    source: markdown.source.slice(leadingNewlines),
    sourceMap: markdown.sourceMap.slice(leadingNewlines),
  }
}

const prependMarkdownMetadata = (metadata: MarkdownMetadata, body: MappedMarkdown): MappedMarkdown => {
  const document = concatenateMappedMarkdown([
    mappedSource(`${generatedFileNotice}\n\n`, metadata.titlePosition),
    mappedSource(`# ${metadata.title}\n\n`, metadata.titlePosition),
    removeLeadingNewlines(body),
  ])
  if (!metadata.frontmatter) {
    return document
  }
  const frontmatter = stringifyYAML(metadata.frontmatter, { lineWidth: -1, noRefs: true })
  const frontmatterPosition = metadata.frontmatterPosition ?? metadata.titlePosition
  return concatenateMappedMarkdown([mappedSource(`---\n${frontmatter}\n---\n\n`, frontmatterPosition), document])
}

export const compileMarkdownModule = async (options: CompileMarkdownModuleOptions): Promise<CompiledMarkdownModule> => {
  const sourceFile = ts.createSourceFile(options.id, options.code, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  const template = findMarkdownTemplate(sourceFile)
  const linkImports = findLinkImports(sourceFile)
  const noteCollections = readNoteCollections(sourceFile)
  const metadata = readMarkdownMetadata(sourceFile)

  if (ts.isNoSubstitutionTemplateLiteral(template)) {
    const compiled = prependMarkdownMetadata(
      metadata,
      mappedTemplateSource(template.text, sourceFile, template.getStart(sourceFile) + 1),
    )
    return { code: `export default ${JSON.stringify(compiled.source)}\n`, ...compiled }
  }

  const interpolations = await Promise.all(
    template.templateSpans.map(async (span) => ({
      ...(await renderMarkdownInterpolation(span.expression, linkImports, noteCollections, options, sourceFile)),
      expressionPosition: sourcePosition(sourceFile, span.expression.getStart(sourceFile)),
      literal: mappedTemplateSource(span.literal.text, sourceFile, span.literal.getStart(sourceFile) + 1),
    })),
  )
  const body = concatenateMappedMarkdown([
    mappedTemplateSource(template.head.text, sourceFile, template.head.getStart(sourceFile) + 1),
    ...interpolations.flatMap((interpolation) => [
      mappedSource(interpolation.value, interpolation.expressionPosition),
      interpolation.literal,
    ]),
  ])
  const compiled = prependMarkdownMetadata(metadata, body)
  const dependencies = new Set(
    interpolations.flatMap((interpolation) =>
      Predicate.isString(interpolation.dependency) ? [interpolation.dependency] : [],
    ),
  )

  const imports = [...dependencies].map((specifier) => `import ${JSON.stringify(specifier)}`).join('\n')

  return { code: `${imports}\nexport default ${JSON.stringify(compiled.source)}\n`, ...compiled }
}

export const readMarkdownTitle = (fileName: string): string => {
  const code = ts.sys.readFile(fileName)
  if (!Predicate.isString(code)) {
    throw new MarkdownCompileError(fileName, 'could not read the linked document')
  }

  const sourceFile = ts.createSourceFile(fileName, code, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  return readMarkdownMetadata(sourceFile).title
}
