import { stringifyYAML } from 'confbox'
import { Predicate, String } from 'effect'
import ts from 'typescript'
import { normalizePath } from 'vite'

import {
  decodeMarkdownLinkReference,
  decodeMarkdownTemplate,
  isMarkdownLinkReference,
  isMarkdownTemplate,
  validateMarkdownMetadata,
} from './runtime.ts'
import type { MarkdownLinkReference, MarkdownMetadata, MarkdownTemplate } from './runtime.ts'

export interface LinkRequest {
  readonly hash: string | undefined
  readonly path: string
  readonly query: string
  readonly text: string | undefined
}

export interface MarkdownSourcePosition {
  readonly column: number
  readonly line: number
}

export interface CompiledMarkdownDocument {
  readonly fileName: string
  readonly source: string
  readonly sourceMap: readonly MarkdownSourcePosition[]
  readonly sourcePath: string
}

interface CompileMarkdownDocumentsOptions {
  readonly directory: string
  readonly modules: unknown
  readonly root: string
}

interface FormatMarkdownLinkOptions {
  readonly destination: string
  readonly request: Pick<LinkRequest, 'hash' | 'text'>
  readonly title: string
}

interface MappedMarkdown {
  readonly source: string
  readonly sourceMap: readonly MarkdownSourcePosition[]
}

interface MarkdownSourceSyntax {
  readonly bodyPosition: MarkdownSourcePosition
  readonly frontmatterPosition: MarkdownSourcePosition
  readonly sourceFile: ts.SourceFile
  readonly template: ts.TemplateLiteral | undefined
  readonly titlePosition: MarkdownSourcePosition
}

interface ResolvedMarkdownDocument {
  readonly body: MarkdownTemplate
  readonly fileName: string
  readonly meta: MarkdownMetadata
  readonly modulePath: string
  readonly sourcePath: string
  readonly syntax: MarkdownSourceSyntax
}

export const generatedFileNotice =
  '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->'

export class MarkdownCompileError extends Error {
  readonly fileName: string
  override readonly name = 'MarkdownCompileError'

  constructor(fileName: string, message: string, options?: ErrorOptions) {
    super(`${fileName}: ${message}`, options)
    this.fileName = fileName
  }
}

export const parseLinkRequest = (id: string): LinkRequest | undefined => {
  const queryIndex = id.indexOf('?')
  if (queryIndex === -1) {
    return undefined
  }

  const path = id.slice(0, queryIndex)
  const query = id.slice(queryIndex + 1)
  const parameters = new URLSearchParams(query)
  if (!path.endsWith('.md.ts') || !parameters.has('link')) {
    return undefined
  }

  return {
    hash: parameters.get('hash') ?? undefined,
    path,
    query,
    text: parameters.get('text') ?? undefined,
  }
}

const escapeLinkText = (text: string): string =>
  text.replaceAll('\\', '\\\\').replaceAll('[', '\\[').replaceAll(']', '\\]')

export const formatMarkdownLink = (options: FormatMarkdownLinkOptions): string => {
  const text = options.request.text ?? options.title
  const hashValue = options.request.hash
  const hash = Predicate.isString(hashValue) && String.isNonEmpty(hashValue) ? `#${encodeURIComponent(hashValue)}` : ''

  return `[${escapeLinkText(text)}](${options.destination}${hash})`
}

export const normalizeMarkdownDirectory = (directory: string): string => {
  const segments = normalizePath(directory)
    .split('/')
    .filter((segment) => String.isNonEmpty(segment) && segment !== '.')

  if (segments.includes('..')) {
    throw new MarkdownCompileError(directory, 'the document directory must stay within the Vite root')
  }

  return segments.join('/')
}

const outputFileName = (directory: string, modulePath: string): string | undefined => {
  const normalizedPath = normalizePath(modulePath).replace(/^\//u, '')
  const prefix = String.isEmpty(directory) ? '' : `${directory}/`
  if (!normalizedPath.startsWith(prefix) || !normalizedPath.endsWith('.md.ts')) {
    return undefined
  }
  return `${normalizedPath.slice(prefix.length, -'.md.ts'.length)}.md`
}

const relativeDestination = (currentFileName: string, targetFileName: string): string => {
  const currentDirectory = currentFileName.split('/').slice(0, -1)
  const target = targetFileName.split('/')
  const firstDifferentSegment = currentDirectory.findIndex((segment, index) => segment !== target[index])
  const sharedSegments = firstDifferentSegment === -1 ? currentDirectory.length : firstDifferentSegment

  return [...currentDirectory.slice(sharedSegments).map(() => '..'), ...target.slice(sharedSegments)].join('/')
}

const sourcePosition = (sourceFile: ts.SourceFile, position: number): MarkdownSourcePosition => {
  const location = sourceFile.getLineAndCharacterOfPosition(position)
  return { column: location.character + 1, line: location.line + 1 }
}

const unwrapExpression = (expression: ts.Expression): ts.Expression => {
  if (
    ts.isAsExpression(expression) ||
    ts.isParenthesizedExpression(expression) ||
    ts.isSatisfiesExpression(expression) ||
    ts.isTypeAssertionExpression(expression)
  ) {
    return unwrapExpression(expression.expression)
  }
  return expression
}

const staticPropertyName = (name: ts.PropertyName): string | undefined =>
  ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name) ? name.text : undefined

const objectProperty = (value: ts.ObjectLiteralExpression, name: string): ts.Expression | undefined => {
  const property = value.properties.find(
    (candidate) => ts.isPropertyAssignment(candidate) && staticPropertyName(candidate.name) === name,
  )
  return property && ts.isPropertyAssignment(property) ? unwrapExpression(property.initializer) : undefined
}

const metadataObject = (expression: ts.Expression): ts.ObjectLiteralExpression | undefined => {
  const value = unwrapExpression(expression)
  if (ts.isObjectLiteralExpression(value)) {
    return value
  }
  if (ts.isCallExpression(value) && value.arguments[0]) {
    const argument = unwrapExpression(value.arguments[0])
    return ts.isObjectLiteralExpression(argument) ? argument : undefined
  }
  return undefined
}

const findMetadataInitializer = (sourceFile: ts.SourceFile): ts.Expression | undefined => {
  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue
    }
    const exported =
      ts.getModifiers(statement)?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false
    if (!exported) {
      continue
    }
    for (const declaration of statement.declarationList.declarations) {
      if (ts.isIdentifier(declaration.name) && declaration.name.text === 'meta' && declaration.initializer) {
        return declaration.initializer
      }
    }
  }
  return undefined
}

const findDefaultExpression = (sourceFile: ts.SourceFile): ts.Expression | undefined => {
  for (const statement of sourceFile.statements) {
    if (ts.isExportAssignment(statement) && statement.isExportEquals !== true) {
      return statement.expression
    }
  }
  return undefined
}

const readMarkdownSourceSyntax = (sourcePath: string): MarkdownSourceSyntax => {
  const code = ts.sys.readFile(sourcePath)
  if (!Predicate.isString(code)) {
    throw new MarkdownCompileError(sourcePath, 'could not read the Markdown source module')
  }

  const sourceFile = ts.createSourceFile(sourcePath, code, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  const defaultExpression = findDefaultExpression(sourceFile)
  const bodyExpression = defaultExpression ? unwrapExpression(defaultExpression) : undefined
  const template = bodyExpression && ts.isTaggedTemplateExpression(bodyExpression) ? bodyExpression.template : undefined
  const bodyPosition = sourcePosition(sourceFile, bodyExpression?.getStart(sourceFile) ?? 0)
  const metadataInitializer = findMetadataInitializer(sourceFile)
  const metadataPosition = sourcePosition(sourceFile, metadataInitializer?.getStart(sourceFile) ?? 0)
  const object = metadataInitializer ? metadataObject(metadataInitializer) : undefined
  const title = object ? objectProperty(object, 'title') : undefined
  const frontmatter = object ? objectProperty(object, 'frontmatter') : undefined

  return {
    bodyPosition,
    frontmatterPosition: frontmatter ? sourcePosition(sourceFile, frontmatter.getStart(sourceFile)) : metadataPosition,
    sourceFile,
    template,
    titlePosition: title ? sourcePosition(sourceFile, title.getStart(sourceFile)) : metadataPosition,
  }
}

const mappedSource = (source: string, position: MarkdownSourcePosition): MappedMarkdown => ({
  source,
  sourceMap: source.split('\n').map(() => position),
})

const mappedTemplateSource = (source: string, sourceFile: ts.SourceFile, startPosition: number): MappedMarkdown => {
  const start = sourcePosition(sourceFile, startPosition)
  return {
    source,
    sourceMap: source.split('\n').map((_line, index) => ({
      column: index === 0 ? start.column : 1,
      line: start.line + index,
    })),
  }
}

const appendMappedMarkdown = (combined: MappedMarkdown, remaining: readonly MappedMarkdown[]): MappedMarkdown => {
  const [chunk, ...rest] = remaining
  if (!chunk) {
    return combined
  }
  if (String.isEmpty(combined.source)) {
    return appendMappedMarkdown(chunk, rest)
  }

  const previousPosition = combined.sourceMap.at(-1)
  if (!previousPosition) {
    return appendMappedMarkdown(chunk, rest)
  }
  const mergedPosition = combined.source.endsWith('\n') ? (chunk.sourceMap[0] ?? previousPosition) : previousPosition
  return appendMappedMarkdown(
    {
      source: `${combined.source}${chunk.source}`,
      sourceMap: [...combined.sourceMap.slice(0, -1), mergedPosition, ...chunk.sourceMap.slice(1)],
    },
    rest,
  )
}

const concatenateMappedMarkdown = (chunks: readonly MappedMarkdown[]): MappedMarkdown =>
  appendMappedMarkdown({ source: '', sourceMap: [] }, chunks)

const markdownLineCount = (source: string): number => source.split('\n').length

const trimMappedMarkdown = (markdown: MappedMarkdown): MappedMarkdown => {
  const source = markdown.source.trim()
  if (String.isEmpty(source)) {
    return { source: '', sourceMap: [] }
  }
  const start = markdown.source.indexOf(source)
  const leadingSource = markdown.source.slice(0, start)
  const leadingLines = leadingSource.split('\n').length - 1
  const sourceMap = markdown.sourceMap.slice(leadingLines, leadingLines + markdownLineCount(source))
  const leadingColumn = leadingSource.slice(leadingSource.lastIndexOf('\n') + 1).length
  const [firstPosition] = sourceMap

  return {
    source,
    sourceMap:
      firstPosition && leadingColumn > 0
        ? [{ column: firstPosition.column + leadingColumn, line: firstPosition.line }, ...sourceMap.slice(1)]
        : sourceMap,
  }
}

const finalizeMappedMarkdown = (markdown: MappedMarkdown): MappedMarkdown => {
  const source = markdown.source.trimEnd()
  const sourceMap = markdown.sourceMap.slice(0, markdownLineCount(source))
  const finalPosition = sourceMap.at(-1)
  return {
    source: `${source}\n`,
    sourceMap: finalPosition ? [...sourceMap, finalPosition] : sourceMap,
  }
}

const readModule = (
  module: unknown,
  sourcePath: string,
): { readonly body: MarkdownTemplate; readonly meta: MarkdownMetadata } => {
  if (!Predicate.isObject(module) || Array.isArray(module)) {
    throw new MarkdownCompileError(sourcePath, 'the Markdown module must export an object')
  }

  const body: unknown = Reflect.get(module, 'default')
  if (!isMarkdownTemplate(body)) {
    throw new MarkdownCompileError(sourcePath, 'the default export must be created with the md tagged template')
  }

  return { body: decodeMarkdownTemplate(body), meta: validateMarkdownMetadata(Reflect.get(module, 'meta')) }
}

const sourcePathFromModulePath = (root: string, modulePath: string): string => {
  const normalizedRoot = normalizePath(root).replace(/\/$/u, '')
  const normalizedModulePath = normalizePath(modulePath)
  if (normalizedModulePath.startsWith(`${normalizedRoot}/`)) {
    return normalizedModulePath
  }
  return `${normalizedRoot}/${normalizedModulePath.replace(/^\//u, '')}`
}

const resolveDocuments = (options: CompileMarkdownDocumentsOptions): readonly ResolvedMarkdownDocument[] => {
  if (!Predicate.isObject(options.modules) || Array.isArray(options.modules)) {
    throw new MarkdownCompileError(options.root, 'the Markdown document collection must be an object')
  }

  const directory = normalizeMarkdownDirectory(options.directory)
  return Object.entries(options.modules)
    .map(([modulePath, module]): ResolvedMarkdownDocument => {
      const sourcePath = sourcePathFromModulePath(options.root, modulePath)
      const fileName = outputFileName(directory, modulePath)
      if (!Predicate.isString(fileName)) {
        throw new MarkdownCompileError(sourcePath, 'the Markdown document is outside the configured directory')
      }
      const loaded = readModule(module, sourcePath)
      return {
        ...loaded,
        fileName,
        modulePath,
        sourcePath,
        syntax: readMarkdownSourceSyntax(sourcePath),
      }
    })
    .toSorted((left, right) => left.fileName.localeCompare(right.fileName))
}

const renderLink = (
  link: MarkdownLinkReference,
  current: ResolvedMarkdownDocument,
  documentsBySourcePath: ReadonlyMap<string, ResolvedMarkdownDocument>,
): string => {
  const targetPath = normalizePath(link.targetPath)
  const target = documentsBySourcePath.get(targetPath)
  if (!target) {
    throw new MarkdownCompileError(
      current.sourcePath,
      `the linked document is outside the configured directory: ${targetPath}`,
    )
  }
  if (!Predicate.isNullish(link.text) && !Predicate.isString(link.text)) {
    throw new MarkdownCompileError(current.sourcePath, 'the Markdown link text must be a string')
  }
  if (!Predicate.isNullish(link.hash) && !Predicate.isString(link.hash)) {
    throw new MarkdownCompileError(current.sourcePath, 'the Markdown link hash must be a string')
  }

  return formatMarkdownLink({
    destination: relativeDestination(current.fileName, target.fileName),
    request: link,
    title: target.meta.title,
  })
}

const renderMarkdownValue = (
  value: unknown,
  current: ResolvedMarkdownDocument,
  documentsBySourcePath: ReadonlyMap<string, ResolvedMarkdownDocument>,
): string => {
  if (Predicate.isNullish(value)) {
    return ''
  }
  if (isMarkdownLinkReference(value)) {
    return renderLink(decodeMarkdownLinkReference(value), current, documentsBySourcePath)
  }
  if (isMarkdownTemplate(value)) {
    const nested = decodeMarkdownTemplate(value)
    if (nested.strings.length !== nested.values.length + 1) {
      throw new MarkdownCompileError(current.sourcePath, 'the Markdown template has an invalid segment count')
    }
    return nested.strings
      .map((segment, index) => `${segment}${renderMarkdownValue(nested.values[index], current, documentsBySourcePath)}`)
      .join('')
      .trim()
  }
  if (Predicate.isBigInt(value) || Predicate.isNumber(value) || Predicate.isString(value)) {
    return `${value}`
  }
  throw new MarkdownCompileError(
    current.sourcePath,
    'md interpolations must produce strings, numbers, links, or Markdown templates',
  )
}

const renderTemplateSource = (
  template: MarkdownTemplate,
  current: ResolvedMarkdownDocument,
  documentsBySourcePath: ReadonlyMap<string, ResolvedMarkdownDocument>,
): string => {
  if (template.strings.length !== template.values.length + 1) {
    throw new MarkdownCompileError(current.sourcePath, 'the Markdown template has an invalid segment count')
  }

  return template.strings
    .map((segment, index) => `${segment}${renderMarkdownValue(template.values[index], current, documentsBySourcePath)}`)
    .join('')
}

const renderMappedBody = (
  current: ResolvedMarkdownDocument,
  documentsBySourcePath: ReadonlyMap<string, ResolvedMarkdownDocument>,
): MappedMarkdown => {
  const { template } = current.syntax
  if (!template || current.body.strings.length !== current.body.values.length + 1) {
    return trimMappedMarkdown(
      mappedSource(renderTemplateSource(current.body, current, documentsBySourcePath), current.syntax.bodyPosition),
    )
  }

  if (ts.isNoSubstitutionTemplateLiteral(template)) {
    return trimMappedMarkdown(
      mappedTemplateSource(
        current.body.strings[0] ?? '',
        current.syntax.sourceFile,
        template.getStart(current.syntax.sourceFile) + 1,
      ),
    )
  }
  if (template.templateSpans.length !== current.body.values.length) {
    return trimMappedMarkdown(
      mappedSource(renderTemplateSource(current.body, current, documentsBySourcePath), current.syntax.bodyPosition),
    )
  }

  const chunks: MappedMarkdown[] = [
    mappedTemplateSource(
      current.body.strings[0] ?? '',
      current.syntax.sourceFile,
      template.head.getStart(current.syntax.sourceFile) + 1,
    ),
  ]
  for (const [index, span] of template.templateSpans.entries()) {
    chunks.push(
      mappedSource(
        renderMarkdownValue(current.body.values[index], current, documentsBySourcePath),
        sourcePosition(current.syntax.sourceFile, span.expression.getStart(current.syntax.sourceFile)),
      ),
      mappedTemplateSource(
        current.body.strings[index + 1] ?? '',
        current.syntax.sourceFile,
        span.literal.getStart(current.syntax.sourceFile) + 1,
      ),
    )
  }
  return trimMappedMarkdown(concatenateMappedMarkdown(chunks))
}

const prependMarkdownMetadata = (current: ResolvedMarkdownDocument, body: MappedMarkdown): MappedMarkdown => {
  const document = concatenateMappedMarkdown([
    mappedSource(`${generatedFileNotice}\n\n`, current.syntax.titlePosition),
    mappedSource(`# ${current.meta.title}\n\n`, current.syntax.titlePosition),
    body,
  ])
  if (!current.meta.frontmatter) {
    return finalizeMappedMarkdown(document)
  }
  const frontmatter = stringifyYAML(current.meta.frontmatter, { lineWidth: -1, noRefs: true })
  return finalizeMappedMarkdown(
    concatenateMappedMarkdown([
      mappedSource(`---\n${frontmatter}\n---\n\n`, current.syntax.frontmatterPosition),
      document,
    ]),
  )
}

export const compileMarkdownDocuments = (
  options: CompileMarkdownDocumentsOptions,
): readonly CompiledMarkdownDocument[] => {
  const documents = resolveDocuments(options)
  const documentsBySourcePath = new Map(documents.map((document) => [document.sourcePath, document]))

  return documents.map((document) => {
    const compiled = prependMarkdownMetadata(document, renderMappedBody(document, documentsBySourcePath))
    return {
      fileName: document.fileName,
      source: compiled.source,
      sourceMap: compiled.sourceMap,
      sourcePath: document.sourcePath,
    }
  })
}
