import { createServer } from 'vite'
import { describe, expect, expectTypeOf, test } from 'vite-plus/test'

import trailingNewlineBody, { meta as trailingNewlineMeta } from './__fixtures__/trailing-newline.md.ts'
import { compileMarkdownDocuments, formatMarkdownLink, parseLinkRequest } from './compiler.ts'
import { defineMeta, defineNote, markdown, markdownDocumentsId, md, noteBody, noteRef } from './index.ts'
import type { MarkdownLinkReference } from './index.ts'

const fixtureRoot = new URL('__fixtures__/', import.meta.url).pathname

describe('md', () => {
  test('preserves Markdown syntax and interpolates TypeScript values', () => {
    // Given
    const title = 'Guide'
    const itemCount = 2

    // When
    const document = md`
# ${title}

Items: ${itemCount}
`

    // Then
    expect(document).toEqual({
      kind: 'vite-plugin-mdts/template',
      strings: ['\n# ', '\n\nItems: ', '\n'],
      values: ['Guide', 2],
    })
  })

  test('emits escaped template delimiters as Markdown code delimiters', () => {
    // Given
    const command = 'vp build'

    // When
    const document = md`Run \`${command}\`.`

    // Then
    expect(document).toEqual({
      kind: 'vite-plugin-mdts/template',
      strings: ['Run `', '`.'],
      values: ['vp build'],
    })
  })
})

describe('Markdown notes', () => {
  test('assigns sequential string indexes while preserving tuple types', () => {
    // Given
    const notes = defineNote([
      {
        body: md`
First **note**.
        `,
        slug: 'first',
      },
      {
        body: md`
Second note.
        `,
        slug: 'second',
      },
    ] as const)

    // Then
    expect(notes).toEqual([
      {
        body: { kind: 'vite-plugin-mdts/template', strings: ['\nFirst **note**.\n        '], values: [] },
        index: '1',
        slug: 'first',
      },
      {
        body: { kind: 'vite-plugin-mdts/template', strings: ['\nSecond note.\n        '], values: [] },
        index: '2',
        slug: 'second',
      },
    ])
    expectTypeOf(notes[0].index).toEqualTypeOf<'1'>()
    expectTypeOf(notes[1].index).toEqualTypeOf<'2'>()
    expectTypeOf(notes[1].slug).toEqualTypeOf<'second'>()
  })

  test('renders references and bodies from the same slug', () => {
    // Given
    const notes = defineNote([
      {
        body: md`
First note.
        `,
        slug: 'first',
      },
      {
        body: md`
Second note.
        `,
        slug: 'second',
      },
    ] as const)

    // Then
    expect(noteRef(notes, 'second')).toBe('[^2]')
    expect(noteBody(notes, 'first')).toEqual({
      kind: 'vite-plugin-mdts/template',
      strings: ['[^1]: ', ''],
      values: [notes[0].body],
    })
  })

  test('rejects duplicate and unknown slugs', () => {
    // Given
    const notes = defineNote([
      {
        body: md`
Known note.
        `,
        slug: 'known',
      },
    ] as const)

    // Then
    expect(() =>
      defineNote([
        {
          body: md`
First note.
          `,
          slug: 'duplicate',
        },
        {
          body: md`
Second note.
          `,
          slug: 'duplicate',
        },
      ] as const),
    ).toThrow('Duplicate Markdown note slug: duplicate')
    expect(() => {
      // @ts-expect-error -- Note slugs are restricted to values inferred from the tuple.
      noteRef(notes, 'unknown')
    }).toThrow('Unknown Markdown note slug: unknown')
  })
})

describe('markdown', () => {
  test('prepends metadata titles and frontmatter and converts link imports', async () => {
    // Given
    const server = await createServer({
      appType: 'custom',
      configFile: false,
      logLevel: 'silent',
      plugins: [markdown({ directory: '.' })],
      root: fixtureRoot,
    })

    // When
    const loaded = await server.ssrLoadModule(markdownDocumentsId)
    const compiled = compileMarkdownDocuments({ directory: '.', modules: loaded.default, root: fixtureRoot })
    await server.close()

    // Then
    const documents = Object.fromEntries(compiled.map((document) => [document.fileName, document.source]))
    const guideDocument = compiled.find((document) => document.fileName === 'guide.md')
    if (!guideDocument) {
      throw new TypeError('expected the compiled guide document')
    }
    const helperLine = guideDocument.source
      .split('\n')
      .findIndex((line) => line.includes('[Details](reference/api.md#api)'))

    expect(guideDocument.sourceMap[helperLine]).toEqual({ column: 3, line: 28 })
    expect(documents).toEqual({
      'guide.md':
        "---\ndescription: Generated from runtime TypeScript metadata.\ntags:\n  - markdown\n  - typescript\ndraft: false\nmetadata:\n  version: '1.0'\n---\n\n<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Guide\n\n[Details](reference/api.md#api)[^1]\n\n[^1]: The link text and this definition share one typed slug.\n",
      'reference/api.md':
        '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Reference\n\nBack to [Guide](../guide.md).\n',
      'trailing-newline.md':
        '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Trailing newline\n\nBody.\n',
    })
  })

  test('trims generated Markdown and appends exactly one trailing newline', () => {
    // Given
    const modules = {
      '/trailing-newline.md.ts': { default: trailingNewlineBody, meta: trailingNewlineMeta },
    }

    // When
    const [compiled] = compileMarkdownDocuments({ directory: '.', modules, root: fixtureRoot })
    if (!compiled) {
      throw new TypeError('expected a compiled Markdown document')
    }

    // Then
    expect(compiled).toMatchObject({
      source:
        '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Trailing newline\n\nBody.\n',
      sourcePath: `${fixtureRoot}trailing-newline.md.ts`,
    })
    expect(compiled.sourceMap).toHaveLength(compiled.source.split('\n').length)
    expect(compiled.sourceMap[4]).toEqual({ column: 4, line: 6 })
  })

  test('validates metadata and compiled module exports at runtime', () => {
    // Then
    expect(() =>
      defineMeta({
        frontmatter: {
          // @ts-expect-error -- Functions are intentionally rejected at the runtime boundary.
          invalid: () => {},
        },
        title: 'Guide',
      }),
    ).toThrow('meta.frontmatter.invalid must contain only strings, numbers, booleans, null, arrays, or objects')
    expect(() =>
      compileMarkdownDocuments({
        directory: '.',
        modules: { '/trailing-newline.md.ts': { default: trailingNewlineBody } },
        root: fixtureRoot,
      }),
    ).toThrow('meta must be an object')
    expect(() =>
      compileMarkdownDocuments({
        directory: '.',
        modules: { '/trailing-newline.md.ts': { default: 'Body.', meta: trailingNewlineMeta } },
        root: fixtureRoot,
      }),
    ).toThrow('the default export must be created with the md tagged template')
  })

  test('requires a valid document collection', () => {
    // Then
    expect(() => compileMarkdownDocuments({ directory: '.', modules: null, root: fixtureRoot })).toThrow(
      'the Markdown document collection must be an object',
    )
  })

  test('rejects documents outside the configured directory', () => {
    // Then
    expect(() =>
      compileMarkdownDocuments({
        directory: 'content',
        modules: {
          '/trailing-newline.md.ts': { default: trailingNewlineBody, meta: trailingNewlineMeta },
        },
        root: fixtureRoot,
      }),
    ).toThrow('the Markdown document is outside the configured directory')
  })

  test('rejects links to documents outside the collected directory', () => {
    // Given
    const missingLink: MarkdownLinkReference = {
      hash: undefined,
      kind: 'vite-plugin-mdts/link',
      targetPath: `${fixtureRoot}missing.md.ts`,
      text: undefined,
    }

    // Then
    expect(() =>
      compileMarkdownDocuments({
        directory: '.',
        modules: {
          '/trailing-newline.md.ts': { default: md`${missingLink}`, meta: trailingNewlineMeta },
        },
        root: fixtureRoot,
      }),
    ).toThrow('the linked document is outside the configured directory')
  })

  test('uses text and hash query parameters for a link import', () => {
    // Given
    const request = {
      hash: 'api',
      path: './reference.md.ts',
      query: 'text=Details&hash=api&link',
      text: 'Details',
    }

    // When
    const parsed = parseLinkRequest('./reference.md.ts?text=Details&hash=api&link')
    const link = formatMarkdownLink({ destination: 'reference.md', request, title: 'Reference' })

    // Then
    expect(parsed).toEqual(request)
    expect(link).toBe('[Details](reference.md#api)')
  })
})
