import { build } from 'vite'
import type { Plugin, Rolldown } from 'vite'
import { describe, expect, expectTypeOf, test } from 'vite-plus/test'

import { compileMarkdownModule, formatMarkdownLink, parseLinkRequest } from './compiler.ts'
import { defineNote, markdown, md, noteBody, noteRef } from './index.ts'

const virtualEntry = '\0vite-plugin-mdts-test-entry'

const virtualEntryPlugin = (): Plugin => ({
  load(id) {
    return id === virtualEntry ? 'export {}' : undefined
  },
  name: 'vite-plugin-mdts-test-entry',
  resolveId(id) {
    return id === virtualEntry ? virtualEntry : undefined
  },
})

describe('md', () => {
  test('preserves Markdown syntax and interpolates TypeScript values', () => {
    // Given
    const title = 'Guide'
    const itemCount = 2

    // When
    const document = md`
# ${title}

Items: ${itemCount}
`

    // Then
    expect(document).toBe('# Guide\n\nItems: 2')
  })

  test('emits escaped template delimiters as Markdown code delimiters', () => {
    // Given
    const command = 'vp build'

    // When
    const document = md`Run \`${command}\`.`

    // Then
    expect(document).toBe('Run `vp build`.')
  })
})

describe('Markdown notes', () => {
  test('assigns sequential string indexes while preserving tuple types', () => {
    // Given
    const notes = defineNote([
      {
        body: md`
First **note**.
        `,
        slug: 'first',
      },
      {
        body: md`
Second note.
        `,
        slug: 'second',
      },
    ] as const)

    // Then
    expect(notes).toEqual([
      { body: 'First **note**.', index: '1', slug: 'first' },
      { body: 'Second note.', index: '2', slug: 'second' },
    ])
    expectTypeOf(notes[0].index).toEqualTypeOf<'1'>()
    expectTypeOf(notes[1].index).toEqualTypeOf<'2'>()
    expectTypeOf(notes[1].slug).toEqualTypeOf<'second'>()
  })

  test('renders references and bodies from the same slug', () => {
    // Given
    const notes = defineNote([
      {
        body: md`
First note.
        `,
        slug: 'first',
      },
      {
        body: md`
Second note.
        `,
        slug: 'second',
      },
    ] as const)

    // Then
    expect(noteRef(notes, 'second')).toBe('[^2]')
    expect(noteBody(notes, 'first')).toBe('[^1]: First note.')
  })

  test('rejects duplicate and unknown slugs', () => {
    // Given
    const notes = defineNote([
      {
        body: md`
Known note.
        `,
        slug: 'known',
      },
    ] as const)

    // Then
    expect(() =>
      defineNote([
        {
          body: md`
First note.
          `,
          slug: 'duplicate',
        },
        {
          body: md`
Second note.
          `,
          slug: 'duplicate',
        },
      ] as const),
    ).toThrow('Duplicate Markdown note slug: duplicate')
    expect(() => {
      // @ts-expect-error -- Note slugs are restricted to values inferred from the tuple.
      noteRef(notes, 'unknown')
    }).toThrow('Unknown Markdown note slug: unknown')
  })
})

describe('markdown', () => {
  test('prepends metadata titles and frontmatter, emits documents, and converts link imports', async () => {
    // Given
    const projectRoot = new URL('__fixtures__/', import.meta.url).pathname
    const generatedAssets: Rolldown.OutputAsset[] = []
    const collectAssets = (): Plugin => ({
      generateBundle(_options, bundle) {
        for (const output of Object.values(bundle)) {
          if (output.type === 'asset') {
            generatedAssets.push(output)
          }
        }
      },
      name: 'vite-plugin-mdts-test-collector',
    })

    // When
    await build({
      build: {
        rolldownOptions: { input: virtualEntry },
        write: false,
      },
      configFile: false,
      logLevel: 'silent',
      plugins: [
        markdown({
          directory: '.',
        }),
        virtualEntryPlugin(),
        collectAssets(),
      ],
      root: projectRoot,
    })

    // Then
    const documents = Object.fromEntries(generatedAssets.map((asset) => [asset.fileName, asset.source]))

    expect(documents).toEqual({
      'guide.md':
        "---\ndescription: Generated from TypeScript metadata.\ntags:\n  - markdown\n  - typescript\ndraft: false\nmetadata:\n  version: '1.0'\n---\n\n<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Guide\n\n[Details](reference/api.md#api)[^1]\n\n[^1]: The link text and this definition share one typed slug.",
      'reference/api.md':
        '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Reference\n\n',
    })
  })

  test('requires frontmatter values to be statically declared', async () => {
    // Given
    const code = `import { md } from 'vite-plugin-mdts'
const description = 'dynamic'
export const meta = { frontmatter: { description }, title: 'Guide' }
export default md\`Body.
\`
`

    // When
    const compile = compileMarkdownModule({
      code,
      id: '/content/dynamic-frontmatter.md.ts',
      resolveLink: () => Promise.resolve(''),
    })

    // Then
    await expect(compile).rejects.toThrow('meta.frontmatter must contain only static property assignments')
  })

  test('requires a static metadata title', async () => {
    // Given
    const code = "import { md } from 'vite-plugin-mdts'\nexport default md`Body.\n`\n"

    // When
    const compile = compileMarkdownModule({
      code,
      id: '/content/missing-title.md.ts',
      resolveLink: () => Promise.resolve(''),
    })

    // Then
    await expect(compile).rejects.toThrow('expected a static meta.title string')
  })

  test('rejects note helper slugs missing from the defined tuple', async () => {
    // Given
    const code = [
      "import { defineNote, md, noteRef } from 'vite-plugin-mdts'",
      "const notes = defineNote([{ body: md`Known note.`, slug: 'known' }] as const)",
      "export const meta = { title: 'Guide' }",
      `export default md\`Body\${noteRef(notes, 'unknown')}\``,
    ].join('\n')

    // When
    const compile = compileMarkdownModule({
      code,
      id: '/content/unknown-note.md.ts',
      resolveLink: () => Promise.resolve(''),
    })

    // Then
    await expect(compile).rejects.toThrow('Unknown Markdown note slug: unknown')
  })

  test('uses text and hash query parameters for a link import', () => {
    // Given
    const request = {
      hash: 'api',
      path: './reference.md.ts',
      query: 'text=Details&hash=api&link',
      text: 'Details',
    }

    // When
    const parsed = parseLinkRequest('./reference.md.ts?text=Details&hash=api&link')
    const link = formatMarkdownLink({ destination: 'reference.md', request, title: 'Reference' })

    // Then
    expect(parsed).toEqual(request)
    expect(link).toBe('[Details](reference.md#api)')
  })
})
