/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface AllTypes {
  col_blob: Uint8Array;
  col_bool: boolean;
  col_int: number;
  col_json: string;
  col_nullable_blob: Uint8Array | null;
  col_nullable_bool: boolean | null;
  col_nullable_int: number | null;
  col_nullable_real: number | null;
  col_nullable_text: string | null;
  col_real: number;
  col_text: string;
}

export interface DB {
  all_types: AllTypes;
}
