/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface AppConfig {
  httpStatus: number;
  id: number;
  maxRetryCount: number;
  updatedAt: string;
  userId: string;
  apiKey: string | null;
  createdAt: string;
  isActive: number;
}

export interface DB {
  app_config: AppConfig;
}
