/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface User {
  created_at: string;
  email: string;
  email_verified: number;
  id: string;
  image: string | null;
  name: string;
  updated_at: string;
}

export interface DB {
  user: User;
}
