name: Setup MoonBit
description: Install the MoonBit toolchain and update the registry.

runs:
  using: composite
  steps:
    - name: Install moonbit
      uses: hustcer/setup-moonbit@90ea2eec0b33fff99a2a1d2825d723deb31eb621 # v1.20
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Update moonbit registry
      shell: bash
      run: moon update
