version: '3'

dotenv:
  - .env.local

tasks:
  default:
    cmds:
      - task --list-all

  rebuild:
    deps:
      - format
    cmds:
      - sudo nix flake update --option access-tokens "github.com=$(gh auth token)"
      - sudo nix run nix-darwin -- switch --flake .

  format:
    cmds:
      - nixfmt flake.nix
