default:
    @just --list

init-podman:
    podman machine ssh --username root rm -f /etc/containers/registries.conf.d/000-shortnames.conf
    podman machine ssh --username root 'curl -L https://raw.githubusercontent.com/totto2727-dotfiles/chezmoi/refs/heads/main/dot_config/containers/registries.conf > /etc/containers/registries.conf'
    podman machine stop && podman machine start
    podman run --rm -it --device /dev/dri --name gpu-info quay.io/slopezpa/fedora-vgpu vulkaninfo

install-vscode-extensions:
    jq -r '.[]' vscode/extentions.json | xargs -I {} code --install-extension {}

dump-vscode-extensions:
    code --list-extensions | jq -R -s 'split("\n") | map(select(length > 0))' > vscode/extensions.json
