import { Effect } from "@totto/function/effect"
import handle from "hono-react-router-adapter/cloudflare-workers"
import { appEffect } from "#@/entry.hono.js"
import { getLoadContext } from "#@/types/react-router.js"
// @ts-ignore -- generated by vite
import * as build from "../build/server"

const app = Effect.gen(function* () {
  const app = yield* appEffect
  return handle(build, app, { getLoadContext })
}).pipe(Effect.runSync)

export default app
