import { Effect, Logger } from "@totto/function/effect"
import handle from "hono-react-router-adapter/cloudflare-workers"
import { appEffect, clerkCrenditionalLive } from "#@/entry.hono.js"
import { getLoadContext } from "#@/types/react-router.js"
// @ts-ignore -- generated by vite
import * as build from "../build/server/index.js"
import { drizzleClientLive } from "./feature/db/drizzle"
import {
  remoteSQLiteClientLive,
  sqliteCrenditionalLive,
} from "./feature/db/sqlite"

const app = await Effect.gen(function* () {
  return handle(build, yield* appEffect, { getLoadContext })
}).pipe(
  Effect.provide(drizzleClientLive),
  Effect.provide(remoteSQLiteClientLive),
  Effect.provide(sqliteCrenditionalLive),
  Effect.provide(clerkCrenditionalLive),
  Effect.provide(Logger.json),
  Effect.runPromise,
)

export default app
