import { Effect } from "@totto/function/effect"
import handle from "hono-react-router-adapter/cloudflare-workers"
import { appEffect } from "#@/entry.hono.js"
import { getLoadContext } from "#@/types/react-router.js"
// @ts-ignore -- generated by vite
import * as build from "../build/server"
import { DrizzleClient, ProdDrizzleClientLive } from "./feature/db/drizzle"
import { HonoSQLiteCrenditionalLive } from "./feature/db/sqlite"

const app = Effect.gen(function* () {
  yield* DrizzleClient
  const app = yield* appEffect
  return handle(build, app, { getLoadContext })
}).pipe(
  Effect.provide(ProdDrizzleClientLive),
  Effect.provide(HonoSQLiteCrenditionalLive),
  Effect.runSync,
)

export default app
