/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { Generated } from "kysely";

export interface Post {
  body: string | null;
  createdAt: Generated<string>;
  id: Generated<number>;
  status: Generated<string>;
  title: string;
  viewCount: Generated<number>;
}

export interface Tag {
  id: Generated<number>;
  name: string;
}

export interface DB {
  post: Post;
  tag: Tag;
}
