default:
    @just --list

init:
    sudo nixos-rebuild switch \
        --flake .#nixos \
        --experimental-features 'nix-command flakes' \
        --option extra-substituters https://install.determinate.systems \
        --option extra-trusted-public-keys cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM=
    chezmoi init https://github.com/totto2727-dotfiles/chezmoi
    chezmoi apply

tailscale:
    sudo tailscale up --ssh --advertise-routes 172.32.0.0/12
