default:
    @just --list

version-up:
    BUMP=$(echo -e "patch\nminor\nmajor" | fzf --prompt="Select version bump> ")
    vp pm version "$BUMP"
    deno run --allow-read --allow-write scripts/sync-jsr.ts
    vp fmt
    git add package.json jsr.json
    git commit -m "up @totto2727/fp $(jq -r .version package.json)"
    git push
