# https://taskfile.dev
version: '3'

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  version-up:
    vars:
      BUMP:
        sh: echo -e "patch\nminor\nmajor" | fzf --prompt="Select version bump> "
    cmds:
      - bun pm version {{.BUMP}}
      - safe-chain bun run scripts/sync-jsr.ts
      - git add package.json jsr.json
      - git commit -m "up @totto2727/fp $(jq -r .version package.json)"
      - git-cliff --include-path "js/package/fp/**/*" -o CHANGELOG.md --tag $(jq -r .version package.json)
      - git add CHANGELOG.md
      - git commit --amend --no-edit
