# https://taskfile.dev
version: '3'

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  version-up:
    vars:
      BUMP:
        sh: echo -e "patch\nminor\nmajor" | fzf --prompt="Select version bump> "
    cmds:
      - vp pm version {{.BUMP}}
      - deno run --allow-read --allow-write scripts/sync-jsr.ts
      - vp fmt
      - git add package.json jsr.json
      - git commit -m "up @totto2727/fp $(jq -r .version package.json)"
      - git push
