/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface OauthNonce {
  expires_at: number
  nonce: string
  state: string
}

export interface DB {
  oauth_nonce: OauthNonce
}
