/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Account {
  access_token: string | null;
  access_token_expires_at: string | null;
  account_id: string;
  created_at: string;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: string | null;
  scope: string | null;
  updated_at: string;
  user_id: string;
}

export interface Session {
  created_at: string;
  expires_at: string;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: string;
  user_agent: string | null;
  user_id: string;
}

export interface User {
  created_at: string;
  email: string;
  email_verified: number;
  id: string;
  image: string | null;
  name: string;
  updated_at: string;
}

export interface Verification {
  created_at: string;
  expires_at: string;
  id: string;
  identifier: string;
  updated_at: string;
  value: string;
}

export interface DB {
  account: Account;
  session: Session;
  user: User;
  verification: Verification;
}
