import { access, readFile, readdir, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { Effect, Predicate } from 'effect'
import { FetchHttpClient, HttpClient } from 'effect/unstable/http'
import { createHtmlRenderer } from 'mdts/comark'
import { markdownDocumentsId } from 'vite-plugin-mdts'
import { afterEach, beforeEach, describe, expect, test } from 'vite-plus/test'

import { buildMarkdown } from './build.ts'
import { loadMdtsConfig } from './config.ts'
import { formatLintResult, lintMarkdown } from './lint.ts'
import { createMarkdownPreview } from './preview.ts'

const projectRoot = fileURLToPath(new URL('__fixtures__/basic/', import.meta.url))
const englishLintProjectRoot = fileURLToPath(new URL('__fixtures__/lint-en/', import.meta.url))
const japaneseLintProjectRoot = fileURLToPath(new URL('__fixtures__/lint-ja/', import.meta.url))
const lintProjectRoot = fileURLToPath(new URL('__fixtures__/lint/', import.meta.url))
const exampleRoot = fileURLToPath(new URL('../../mdts-example/', import.meta.url))
const englishLintOutputDirectory = fileURLToPath(new URL('__fixtures__/lint-en/dist/', import.meta.url))
const japaneseLintOutputDirectory = fileURLToPath(new URL('__fixtures__/lint-ja/dist/', import.meta.url))
const lintOutputDirectory = fileURLToPath(new URL('__fixtures__/lint/dist/', import.meta.url))
const outputDirectory = fileURLToPath(new URL('__fixtures__/basic/dist/', import.meta.url))

const cleanOutput = async (): Promise<void> => {
  await Promise.all([
    rm(englishLintOutputDirectory, { force: true, recursive: true }),
    rm(japaneseLintOutputDirectory, { force: true, recursive: true }),
    rm(lintOutputDirectory, { force: true, recursive: true }),
    rm(outputDirectory, { force: true, recursive: true }),
  ])
}

const moduleSource = (value: unknown): string => {
  if (!Predicate.isObject(value)) {
    throw new TypeError('expected a Markdown module')
  }
  const source = Reflect.get(value, 'default')
  if (!Predicate.isString(source)) {
    throw new TypeError('expected a Markdown default export')
  }
  return source
}

beforeEach(cleanOutput)
afterEach(cleanOutput)

describe('mdts', () => {
  test('enables markdownlint and selects the English textlint preset by default', async () => {
    // When
    const config = await loadMdtsConfig({ command: 'build', root: projectRoot })

    // Then
    expect(config.lint.markdownlint).toMatchObject({ config: { default: true } })
    expect(config.lint.textlint).toMatchObject({ preset: 'en' })
  })

  test('builds Markdown assets without loading vite.config.ts', async () => {
    // When
    await buildMarkdown({ root: projectRoot })

    // Then
    const guide = await readFile(`${outputDirectory}/guide.md`, 'utf-8')
    const plugins = await readFile(`${outputDirectory}/plugins.md`, 'utf-8')
    const reference = await readFile(`${outputDirectory}/reference/api.md`, 'utf-8')
    const outputs = await readdir(outputDirectory, { recursive: true })

    expect(guide).toBe(
      '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Guide\n\nRead the [API Reference](reference/api.md).',
    )
    expect(plugins).toBe(
      '---\nname: preview-plugins\ndescription: Verifies frontmatter and configured Comark plugins in preview.\nallowed-tools: Read\n---\n\n<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# Preview plugins\n\nConfigured plugins are rendered in the preview.[^1]\n\n[^1]: This footnote is enabled through mdts.config.ts.\n\n> [!WARNING]\n  Alerts use GitHub-compatible markup and styles.',
    )
    expect(reference).toBe(
      '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n\n# API Reference\n\nThe API is ready.',
    )
    expect(outputs).not.toContain('index.html')
    expect(outputs.every((fileName) => !fileName.endsWith('.js'))).toBe(true)
  })

  test('lints generated Markdown with configured JS APIs and maps diagnostics to .md.ts lines', async () => {
    // When
    const result = await lintMarkdown({ root: lintProjectRoot })

    // Then
    expect(result.errorCount).toBe(2)
    expect(result.diagnostics).toMatchObject([
      {
        engine: 'textlint',
        filePath: 'content/lint-target.md.ts',
        line: 7,
        ruleId: 'writing/no-forbidden-word',
        severity: 'error',
      },
      {
        engine: 'markdownlint',
        filePath: 'content/lint-target.md.ts',
        line: 7,
        ruleId: 'MD013',
        severity: 'error',
      },
    ])
    expect(formatLintResult(result)).toContain('content/lint-target.md.ts:7:')
    expect(formatLintResult(result)).toContain('(markdownlint/MD013)')
    await expect(access(lintOutputDirectory)).rejects.toThrow()
  })

  test('uses slopless for the default English textlint preset', async () => {
    // When
    const result = await lintMarkdown({ root: englishLintProjectRoot })

    // Then
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        engine: 'textlint',
        filePath: 'content/english.md.ts',
        line: 7,
        ruleId: 'slopless/cliches',
      }),
    )
    expect(
      result.diagnostics.every((diagnostic) => !diagnostic.ruleId.startsWith('preset-ja-technical-writing/')),
    ).toBe(true)
    await expect(access(englishLintOutputDirectory)).rejects.toThrow()
  })

  test('uses technical writing rules only when the Japanese textlint preset is selected', async () => {
    // When
    const result = await lintMarkdown({ root: japaneseLintProjectRoot })

    // Then
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        engine: 'textlint',
        filePath: 'content/japanese.md.ts',
        line: 7,
        ruleId: 'preset-ja-technical-writing/no-hankaku-kana',
      }),
    )
    expect(result.diagnostics.every((diagnostic) => !diagnostic.ruleId.startsWith('slopless/'))).toBe(true)
    await expect(access(japaneseLintOutputDirectory)).rejects.toThrow()
  })

  test('loads preview documents for Comark HTML rendering', async () => {
    // Given
    const server = await createMarkdownPreview({ root: projectRoot })

    try {
      // When
      const loaded = await server.ssrLoadModule(markdownDocumentsId)
      const modules: unknown = loaded.default
      if (!Predicate.isObject(modules)) {
        throw new TypeError('expected the Markdown document collection')
      }
      const renderHtml = createHtmlRenderer()
      const guide = moduleSource(Reflect.get(modules, '/content/guide.md.ts'))
      const reference = moduleSource(Reflect.get(modules, '/content/reference/api.md.ts'))

      // Then
      await expect(renderHtml(guide)).resolves.toBe(
        '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n<h1 id="guide">Guide</h1>\n<p>Read the <a href="reference/api.md">API Reference</a>.</p>',
      )
      await expect(renderHtml(reference)).resolves.toBe(
        '<!-- AI agents: This file is generated by mdts. Do not edit it directly. Edit the source .md.ts file instead. -->\n<h1 id="api-reference">API Reference</h1>\n<p>The API is ready.</p>',
      )
    } finally {
      await server.close()
    }
  })

  test('serves preview HTML at normal document paths', async () => {
    // Given
    const server = await createMarkdownPreview({ root: projectRoot })

    try {
      await server.listen()
      const previewUrl = server.resolvedUrls?.local[0]
      if (Predicate.isNullish(previewUrl)) {
        throw new TypeError('expected a preview URL')
      }

      // When
      const requestDocument = Effect.gen(function* () {
        const client = yield* HttpClient.HttpClient
        const response = yield* client.get(new URL('/reference/api.md', previewUrl).href)
        return { body: yield* response.text, status: response.status }
      }).pipe(Effect.provide(FetchHttpClient.layer))
      // oxlint-disable-next-line rules/no-effect-runtime-run -- Test boundary executes one preview HTTP request workflow.
      const response = await Effect.runPromise(requestDocument)

      // Then
      expect(response.status).toBe(200)
      expect(response.body).toContain('<title>mdts preview</title>')
      expect(response.body).toContain('github-markdown-css')
      expect(response.body).toContain('katex.min.css')
      expect(response.body).toContain('main { width: 100%;')
      expect(response.body).not.toContain('width: min(100%, 60rem)')
      expect(response.body).toContain('article.markdown-body { background-color: transparent; }')
    } finally {
      await server.close()
    }
  })

  test('applies configured Comark plugins to preview documents', async () => {
    // Given
    const server = await createMarkdownPreview({ root: projectRoot })

    try {
      await server.listen()
      const previewUrl = server.resolvedUrls?.local[0]
      if (Predicate.isNullish(previewUrl)) {
        throw new TypeError('expected a preview URL')
      }

      // When
      const requestDocuments = Effect.gen(function* () {
        const client = yield* HttpClient.HttpClient
        const response = yield* client.get(new URL('/__mdts/documents', previewUrl).href)
        return { body: yield* response.text, status: response.status }
      }).pipe(Effect.provide(FetchHttpClient.layer))
      // oxlint-disable-next-line rules/no-effect-runtime-run -- Test boundary executes one preview HTTP request workflow.
      const response = await Effect.runPromise(requestDocuments)
      const documents: unknown = JSON.parse(response.body)
      if (!Array.isArray(documents)) {
        throw new TypeError('expected preview documents')
      }
      const previewDocuments = documents as readonly unknown[]
      const pluginDocument = previewDocuments.find(
        (document) => Predicate.isObject(document) && Reflect.get(document, 'fileName') === 'plugins.md',
      )
      if (!Predicate.isObject(pluginDocument)) {
        throw new TypeError('expected the plugin preview document')
      }
      const html: unknown = Reflect.get(pluginDocument, 'html')
      if (!Predicate.isString(html)) {
        throw new TypeError('expected rendered plugin HTML')
      }

      // Then
      expect(response.status).toBe(200)
      expect(html).toMatch(/^<pre language="yaml"/u)
      expect(html).toContain('<pre language="yaml"><code class="language-yaml">')
      expect(html).toContain('allowed-tools: Read')
      expect(html).toContain('<h1 id="preview-plugins">Preview plugins</h1>')
      expect(html).toContain('footnote')
      expect(html).toContain('class="markdown-alert markdown-alert-warning"')
      expect(html.indexOf('language-yaml')).toBeLessThan(html.indexOf('id="preview-plugins"'))
      expect(html.indexOf('id="preview-plugins"')).toBeLessThan(html.indexOf('Configured plugins are rendered'))
    } finally {
      await server.close()
    }
  })

  test('renders every included Comark integration with only mdts installed', async () => {
    // Given
    const server = await createMarkdownPreview({ root: exampleRoot })

    try {
      await server.listen()
      const previewUrl = server.resolvedUrls?.local[0]
      if (Predicate.isNullish(previewUrl)) {
        throw new TypeError('expected a preview URL')
      }

      // When
      const requestDocuments = Effect.gen(function* () {
        const client = yield* HttpClient.HttpClient
        const response = yield* client.get(new URL('/__mdts/documents', previewUrl).href)
        return { body: yield* response.text, status: response.status }
      }).pipe(Effect.provide(FetchHttpClient.layer))
      // oxlint-disable-next-line rules/no-effect-runtime-run -- Test boundary executes one preview HTTP request workflow.
      const response = await Effect.runPromise(requestDocuments)
      const documents: unknown = JSON.parse(response.body)
      if (!Array.isArray(documents)) {
        throw new TypeError('expected preview documents')
      }
      const previewDocuments = documents as readonly unknown[]
      const syntaxDocument = previewDocuments.find(
        (document) => Predicate.isObject(document) && Reflect.get(document, 'fileName') === 'markdown-syntax.md',
      )
      if (!Predicate.isObject(syntaxDocument)) {
        throw new TypeError('expected the Markdown syntax preview document')
      }
      const html: unknown = Reflect.get(syntaxDocument, 'html')
      if (!Predicate.isString(html)) {
        throw new TypeError('expected rendered Markdown syntax HTML')
      }

      // Then
      expect(response.status).toBe(200)
      expect(html).toContain('class="katex"')
      expect(html).toContain('class="mermaid"')
      expect(html).toContain('<svg')
      expect(html).toContain('class="shiki')
      expect(html).toContain('class="footnote-ref"')
    } finally {
      await server.close()
    }
  }, 20_000)
})
