/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Account {
  accessToken: string | null
  accessTokenExpiresAt: string | null
  accountId: string
  createdAt: string
  id: string
  idToken: string | null
  password: string | null
  providerId: string
  refreshToken: string | null
  refreshTokenExpiresAt: string | null
  scope: string | null
  updatedAt: string
  userId: string
}

export interface Jwks {
  createdAt: string
  id: string
  privateKey: string
  publicKey: string
}

export interface OauthAccessToken {
  accessToken: string
  clientId: string
  createdAt: string
  expiresAt: string
  id: string
  refreshToken: string | null
  scope: string | null
  updatedAt: string
  userId: string
}

export interface OauthApplication {
  clientId: string
  clientSecret: string
  createdAt: string
  id: string
  name: string
  redirectUris: string
  updatedAt: string
  userId: string
}

export interface OauthConsent {
  clientId: string
  createdAt: string
  id: string
  scope: string | null
  updatedAt: string
  userId: string
}

export interface Passkey {
  aaguid: string | null
  backedUp: number
  counter: number
  createdAt: string
  credentialID: string
  deviceType: string
  id: string
  name: string | null
  publicKey: string
  transports: string | null
  updatedAt: string
  userId: string
}

export interface Session {
  createdAt: string
  expiresAt: string
  id: string
  ipAddress: string | null
  token: string
  updatedAt: string
  userAgent: string | null
  userId: string
}

export interface User {
  createdAt: string
  email: string
  emailVerified: number
  id: string
  image: string | null
  name: string
  updatedAt: string
}

export interface Verification {
  createdAt: string
  expiresAt: string
  id: string
  identifier: string
  updatedAt: string
  value: string
}

export interface DB {
  account: Account
  jwks: Jwks
  oauthAccessToken: OauthAccessToken
  oauthApplication: OauthApplication
  oauthConsent: OauthConsent
  passkey: Passkey
  session: Session
  user: User
  verification: Verification
}
