// Package codegen generates kysely-codegen-compatible TypeScript types
// from an Atlas *schema.Realm.
package main

import (
	"fmt"
	"sort"
	"strings"
	"unicode"

	"ariga.io/atlas/sql/schema"
)

// GenerateOptions holds configuration options for the code generator.
type GenerateOptions struct {
	// CaseMode controls column name casing: "camel", "snake", or "none".
	CaseMode string
}

// GenerateKysely generates a kysely-codegen compatible TypeScript string
// from a *schema.Realm produced by the HCL loader.
func GenerateKysely(realm *schema.Realm, opts GenerateOptions) (string, error) {
	var sb strings.Builder

	// --- Collect all tables across schemas ---
	type tableInfo struct {
		name  string
		table *schema.Table
	}
	var tables []tableInfo
	for _, s := range realm.Schemas {
		for _, table := range s.Tables {
			tables = append(tables, tableInfo{name: table.Name, table: table})
		}
	}

	// Sort tables alphabetically
	sort.Slice(tables, func(i, j int) bool {
		return tables[i].name < tables[j].name
	})

	// --- Check if any column needs Generated<> wrapper ---
	needsGenerated := false
	for _, ti := range tables {
		for _, col := range ti.table.Columns {
			if isGenerated(col) {
				needsGenerated = true
				break
			}
		}
		if needsGenerated {
			break
		}
	}

	// --- JSDoc header ---
	sb.WriteString("/**\n")
	sb.WriteString(" * This file was generated by kysely-codegen.\n")
	sb.WriteString(" * Please do not edit it manually.\n")
	sb.WriteString(" */\n")
	sb.WriteString("\n")

	// --- Import Generated type if needed ---
	if needsGenerated {
		sb.WriteString("import type { Generated } from \"kysely\";\n")
		sb.WriteString("\n")
	}

	type entry struct {
		tableName     string
		interfaceName string
	}
	var entries []entry

	for _, ti := range tables {
		pascal := toPascalCase(ti.name)
		entries = append(entries, entry{tableName: ti.name, interfaceName: pascal})

		// Sort columns alphabetically
		cols := make([]*schema.Column, len(ti.table.Columns))
		copy(cols, ti.table.Columns)
		sort.Slice(cols, func(i, j int) bool {
			return cols[i].Name < cols[j].Name
		})

		// --- interface ---
		fmt.Fprintf(&sb, "export interface %s {\n", pascal)
		for _, col := range cols {
			ts := columnToTsType(col)
			colName := convertColumnName(col.Name, opts.CaseMode)
		fmt.Fprintf(&sb, "  %s: %s;\n", colName, ts.innerType())
		}
		sb.WriteString("}\n\n")
	}

	// --- DB interface ---
	sb.WriteString("export interface DB {\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "  %s: %s;\n", e.tableName, e.interfaceName)
	}
	sb.WriteString("}\n")

	return sb.String(), nil
}

// toPascalCase converts snake_case to PascalCase.
// "user_profiles" → "UserProfiles"
func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

// convertColumnName converts a column name according to the given case mode.
func convertColumnName(name, caseMode string) string {
	switch caseMode {
	case "camel":
		return toCamelCase(name)
	case "snake", "none":
		return name
	default:
		return toCamelCase(name)
	}
}

// toCamelCase converts snake_case to camelCase.
// "access_token" → "accessToken"
func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})
	for i, p := range parts {
		if i == 0 {
			continue
		}
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
