// Package codegen generates kysely-codegen-compatible TypeScript types
// from an Atlas *schema.Realm.
package main

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"ariga.io/atlas/sql/schema"
)

// GenerateOptions holds configuration options for the code generator.
//
// The fields mirror the corresponding kysely-codegen CLI flags 1:1.
type GenerateOptions struct {
	// CamelCase, when true, applies Kysely's CamelCasePlugin (default options,
	// upperCase=false) to column names, the DB-interface key for each table,
	// and the source identifier feeding the table interface name. This is the
	// exact transform applied by kysely-codegen's transformer.transformName
	// (`context.camelCase ? toKyselyCamelCase(name) : name`).
	CamelCase bool
}

// identifierRegexp mirrors kysely-codegen's serializer IDENTIFIER_REGEXP
// (`^[$A-Z_a-z][\w$]*$`). Keys that fail the test must be wrapped in
// double quotes when emitted as TS object-type properties.
var identifierRegexp = regexp.MustCompile(`^[$A-Z_a-z][\w$]*$`)

// nonWordCharRegexp mirrors the JS regex `[^\w$]` (ASCII semantics): every
// character that is not a word character or `$`. Used by tableInterfaceName
// to mimic SymbolCollection.set's `id.replaceAll(/[^\w$]/g, '_')`.
var nonWordCharRegexp = regexp.MustCompile(`[^\w$]`)

// GenerateKysely generates a kysely-codegen compatible TypeScript string
// from a *schema.Realm produced by the HCL loader.
func GenerateKysely(realm *schema.Realm, opts GenerateOptions) (string, error) {
	type tableEntry struct {
		identifier    string // post-transformName key (DB interface)
		interfaceName string // PascalCase TS interface name
		table         *schema.Table
	}

	var tables []tableEntry
	for _, s := range realm.Schemas {
		for _, t := range s.Tables {
			id := transformName(t.Name, opts.CamelCase)
			tables = append(tables, tableEntry{
				identifier:    id,
				interfaceName: tableInterfaceName(id),
				table:         t,
			})
		}
	}

	// transformer.transformTables sorts tableNodes by interface name with localeCompare.
	sort.SliceStable(tables, func(i, j int) bool {
		return localeKeyLess(tables[i].interfaceName, tables[j].interfaceName)
	})

	needsGenerated := false
	for _, ti := range tables {
		for _, col := range ti.table.Columns {
			if isGenerated(col) {
				needsGenerated = true
				break
			}
		}
		if needsGenerated {
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("/**\n")
	sb.WriteString(" * This file was generated by kysely-codegen.\n")
	sb.WriteString(" * Please do not edit it manually.\n")
	sb.WriteString(" */\n\n")

	if needsGenerated {
		sb.WriteString("import type { Generated } from \"kysely\";\n\n")
	}

	for _, ti := range tables {
		// serializer.serializeObjectExpression sorts each interface's
		// properties by key with localeCompare.
		type prop struct{ key, value string }
		props := make([]prop, 0, len(ti.table.Columns))
		for _, col := range ti.table.Columns {
			ts := columnToTsType(col)
			props = append(props, prop{
				key:   transformName(col.Name, opts.CamelCase),
				value: ts.innerType(),
			})
		}
		sort.SliceStable(props, func(i, j int) bool {
			return localeKeyLess(props[i].key, props[j].key)
		})

		fmt.Fprintf(&sb, "export interface %s {\n", ti.interfaceName)
		for _, p := range props {
			fmt.Fprintf(&sb, "  %s: %s;\n", serializeKey(p.key), p.value)
		}
		sb.WriteString("}\n\n")
	}

	// createDatabaseExportNode sorts DB-interface entries by `key`
	// (= identifier after transformName) with localeCompare.
	dbEntries := make([]tableEntry, len(tables))
	copy(dbEntries, tables)
	sort.SliceStable(dbEntries, func(i, j int) bool {
		return localeKeyLess(dbEntries[i].identifier, dbEntries[j].identifier)
	})

	sb.WriteString("export interface DB {\n")
	for _, ti := range dbEntries {
		fmt.Fprintf(&sb, "  %s: %s;\n", serializeKey(ti.identifier), ti.interfaceName)
	}
	sb.WriteString("}\n")

	return sb.String(), nil
}

// transformName mirrors kysely-codegen's transformer.transformName:
// applies the camelCase transform when the flag is on, else identity.
func transformName(name string, camelCase bool) string {
	if camelCase {
		return toKyselyCamelCase(name)
	}
	return name
}

// tableInterfaceName mirrors kysely-codegen's SymbolCollection.set for
// the default `kysely-pascal-case` identifier style: replace non-word
// characters with `_`, then PascalCase.
func tableInterfaceName(identifier string) string {
	return toKyselyPascalCase(replaceNonWordChars(identifier))
}

// toKyselyCamelCase ports kysely-codegen's toKyselyCamelCase, which is
// `new CaseConverter().toCamelCase(s)` and ultimately reduces to
// `createCamelCaseMapper({})` (default options, upperCase=false) from
// kysely's plugin/camel-case/camel-case.js.
//
// kysely-codegen never overrides upperCase, so the
// `isAllUpperCaseSnakeCase` pre-lowercase branch in the JS source is
// dead in this context and intentionally not ported.
func toKyselyCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	var sb strings.Builder
	sb.Grow(len(s))
	sb.WriteByte(s[0])
	for i := 1; i < len(s); i++ {
		ch := s[i]
		prev := s[i-1]
		if ch == '_' {
			continue
		}
		if prev == '_' {
			sb.WriteByte(byte(unicode.ToUpper(rune(ch))))
		} else {
			sb.WriteByte(ch)
		}
	}
	return sb.String()
}

// toKyselyPascalCase mirrors kysely-codegen's toKyselyPascalCase:
// `toUpperFirst(toKyselyCamelCase(s))`.
func toKyselyPascalCase(s string) string {
	camel := toKyselyCamelCase(s)
	if len(camel) == 0 {
		return camel
	}
	var sb strings.Builder
	sb.Grow(len(camel))
	sb.WriteByte(byte(unicode.ToUpper(rune(camel[0]))))
	sb.WriteString(camel[1:])
	return sb.String()
}

// replaceNonWordChars implements `s.replaceAll(/[^\w$]/g, '_')`.
func replaceNonWordChars(s string) string {
	return nonWordCharRegexp.ReplaceAllString(s, "_")
}

// serializeKey mirrors TypeScriptSerializer.serializeKey: emit the key
// bare when it matches IDENTIFIER_REGEXP, otherwise wrap in double quotes
// (JSON-style).
func serializeKey(key string) string {
	if identifierRegexp.MatchString(key) {
		return key
	}
	return strconv.Quote(key)
}

// localeKeyLess approximates `String.prototype.localeCompare` on ASCII
// identifiers in the en-US locale: primary level is case-insensitive,
// with the secondary level placing lowercase before uppercase (the en-US
// ICU default). This is the comparator used by kysely-codegen's
// serializeObjectExpression and createDatabaseExportNode property sorts
// and by transformer.transformTables interface-name sort.
func localeKeyLess(a, b string) bool {
	la, lb := strings.ToLower(a), strings.ToLower(b)
	if la != lb {
		return la < lb
	}
	// On case-only tie, lowercase (the higher byte value) sorts first.
	return a > b
}
