import "./src/access-group.js"
import "./src/access-policy.js"
import "./src/identity-provider.js"
import "./src/argocd/access-application.js"
import "./src/gitea/access-application.js"
import "./src/mcp/access-application.js"
import "./src/mcp/access-policy.js"
import "./src/mcp/workers.js"
