import "./src/access-group.ts"
import "./src/access-policy.ts"
import "./src/identity-provider.ts"
import "./src/argocd/access-application.ts"
import "./src/gitea/access-application.ts"
import "./src/mcp/access-application.ts"
import "./src/mcp/access-policy.ts"
import "./src/mcp/workers.ts"
