name: cloudflare
description: A minimal TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: cloudflare-typescript
