name: cloudflare
description: A minimal TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
    typescript: false
    nodeargs: "--import tsx/esm"
config:
  pulumi:tags:
    value:
      pulumi:template: cloudflare-typescript
