name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          enable-cache: true

      - name: Install moonbit
        uses: hustcer/setup-moonbit@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update moonbit registry
        run: moon update

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: .node-version
          cache: true

      - name: Install package
        run: vp install

      - name: Init gritql
        run: vp exec grit init

      - name: Run check, build, and test
        run: vp run -r prebuild && vp run -r check && vp run -r test && vp run -r build
