name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-moonbit

      - uses: ./.github/actions/setup-typescript

      - name: Run check, build, and test
        run: devbox run -- 'vp run -r prebuild && vp run -r check && vp run -r test && vp run -r build'
