name: Publish @totto2727/fp
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          enable-cache: true

      - name: Install package
        run: vp install

      - name: Publish jsr:@totto2727/fp
        run: |
          cd js/package/fp && vpx jsr publish

      - name: Publish npm:@totto2727/fp
        run: |
          cd js/package/fp && vp pm publish
