name: Publish @totto2727/fp
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-nix

      - uses: ./.github/actions/setup-typescript
        with:
          install-args: --filter @totto2727/fp...

      - name: Publish jsr:@totto2727/fp
        uses: ./.github/actions/publish-jsr
        with:
          working-directory: js/package/fp

      - name: Publish npm:@totto2727/fp
        uses: ./.github/actions/publish-npm
        with:
          working-directory: js/package/fp
