name: Publish @totto2727/mdt
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-devbox

      - uses: ./.github/actions/setup-typescript
        with:
          install-args: --filter @totto2727/mdt...

      - name: Build @totto2727/mdt
        shell: bash
        run: |
          eval "$(devbox shellenv)"
          vp run -t @totto2727/mdt#build

      - name: Publish npm:@totto2727/mdt
        uses: ./.github/actions/publish-npm
        with:
          working-directory: js/app/mdt
